### ISSUE TITLE
Make regex_syntax generic to all regexes, not just those supported by `regex`

### ISSUE THREAD

**Issue by LeoDog896** [rust-lang/regex#1094]
#### Describe your feature request

Move `Unsupported` errors away from `regex_syntax` and towards the `regex` crate, to allow `regex_syntax` to be a full AST parsing implementation similar to `PCRE` regexes, allowing for features usually unsupported by `regex` like backreferences.

Note: **This is out of scope for the main goal of the crate**, (and I fully understand if this is closed), however, as it stands, there is no feature complete AST regex syntax parser, and, given that `regex_syntax` is its own standalone crate, it seems fitting to add to the future set.

**Comment by BurntSushi** [comment]
Others have requested something narrower than what you're asking (like supporting specific features like look-around) and I've turned them down. Similarly, I'll turn this request down as well. What you're asking is specifically an unbounded goal that would require an enormous amount of effort. I don't have the time or inclination to support such a task. My back-of-the-envelope guess is that this would make the parser an order of magnitude more complex. So this doesn't fall into the "it makes sense because regex-syntax is its own crate" bucket from my perspective. It more likely falls into the "it needs to be its own distinct project" bucket.
