### ISSUE TITLE
The master branch has been rolled back.

### ISSUE THREAD

**Issue by bluss** [rust-lang/regex#112]
@BurntSushi do you know what happened? Best would be if you could restore master again from a local clone.

**Comment by BurntSushi** [comment]
Well, I have egg on my face. I accidentally force pushed my local master branch which was apparently quite old. I did it by accident because I forced push a branch I was working on (which I really shouldn't be doing) without specifying the branch. Couple that with a bad value for `git.push.default` (`matching`), and, well, you have nastiness.

It seems to be restored. This was a life saver: http://pablofabregat.com/git/yes-you-can-revert-a-git-push-force/
