### ISSUE TITLE
Another NotWordBoundaryAscii Bug

### ISSUE THREAD

**Issue by SeanRBurton** [rust-lang/regex#271]
Matching `"$(?-u:\\B)"`, i.e. `Concat([EndText, NotWordBoundaryAscii])` against `"\u{5c124}\u{b576c}"` gives no match with the default matcher, but matches at `(8, 8)` with the NFA.

edit:

also `"(?m:$)|(?-u:\\b)"`, i.e. `Alternate([EndLine, WordBoundaryAscii])` against `"\u{6084e}"` gives `(4, 4)` and `(1, 1)` as the two match locations.

edit2:

More bugs:

| Regex String | Expr | Text | Default | NFA |
| --- | --- | --- | --- | --- |
| "(?i-u:\x00)|$" | Alternate([LiteralBytes {  bytes: [0], casei: true }, EndText]) | "\u{e682f}" | (4, 4) | (1, 1) |
| "(?i-u:y)|(?m:$)" | Alternate([LiteralBytes { bytes: [121], casei: true }, EndLine]) | "\u{b4331}" | (4, 4) | (1, 1) |
| "(?u:\b)^(?-u:X)" | Concat([WordBoundary, StartText, LiteralBytes { bytes: [88], casei: false }]) | "X" | None | (0, 1) |
|  |  |  |  |  |

**Comment by BurntSushi** [comment]
Thanks! Sorry it took me so long, but these bugs are gnarly. I converted your issue into these regression tests:

```rust
mat!(end_not_wb, u!(r"$(?-u:\B)"), "\u{5c124}\u{b576c}", Some((8, 8))); // xxx
mat!(endl_or_wb, u!(r"(?m:$)|(?-u:\b)"), "\u{6084e}", Some((4, 4)));
mat!(zero_or_end, u!(r"(?i-u:\x00)|$"), "\u{e682f}", Some((4, 4)));
mat!(y_or_endl, u!(r"(?i-u:y)|(?m:$)"), "\u{b4331}", Some((4, 4)));
mat!(wb_start_x, u!(r"(?u:\b)^(?-u:X)"), "X", Some((0, 1))); // xxx
```

I was only able to observe the first and last tests fail. The middle three seem to work fine.

The actual bug here was that start states were not computing word boundary flags correctly. I think I finally have a fix for it.
