### ISSUE TITLE
Feature request: JIT

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/regex#325]
This is a feature request for what may well be another very large performance improvement: JIT compilation.

The idea is simple: Currently, a regex is compiled to bytecode which is then interpreted.  Instead, it can be compiled to native machine code.  It would be nice to support at least x86 and ARM.  The V8 JavaScript engine does this.

**Comment by BurntSushi** [comment]
It's actually not clear at all that this would be a performance improvement. This regex engine is already reasonably competitive with PCRE2's JIT. (There are benchmarks in this repo, including pcre1, pcre2, oniguruma, tcl and re2.)

Building a good JIT takes years of effort. It should be built outside this crate before we even start the conversation of whether it belongs here or not.

**Comment by BurntSushi** [comment]
> Currently, a regex is compiled to bytecode which is then interpreted.

This is an accurate description of the Pike VM, but the overheard of intepretation is mostly removed in the DFA.

**Comment by wareya** [comment]
I played around with using cranelift to JIT regexes, and the results are basically:
- For NFAs, all the performance benefit you can get from JITing is actually coming from the process of performing epsilon closure upfront instead of on the fly. This preprocessing step is potentially quadratic. But it's a pretty big performance boost. Not JIT-related though. JITing the graphs that come out of epsilon closure for NFAs didn't result in any real performance benefit. This is REALLY worth looking into. It was faster than the lazy DFAs. Not JIT though, again.
- For DFAs, the performance benefit of throwing them into a JIT was dramatic and unignorable. I don't remember the exact numbers but it was something vaguely like a 10x improvement over the lazy DFAs. For use cases where the upfront potentially exponential cost is swallowable (like lexers and parsers) it would be an immediate win.

I was investigating some alterations to the NFA part to reduce memory usage during epsilon closure, but I burned out while doing it so the code is currently half-broken. If anyone's curious though I can dig it up and go into more detail.

**Comment by BurntSushi** [comment]
I'm very skeptical of the 10x improvement over DFAs. The `regex` crate already does at least as good as PCRE2's JIT when using lazy DFAs. It's possible the benchmarking methology is off somehow. If you or anyone really wants to dive into it, I suggest adding a JIT enabled engine to [rebar](https://github.com/BurntSushi/rebar) and baking them off that way. Submit a PR to rebar, and then anyone should be able to reproduce your results.

**Comment by wareya** [comment]
Ah, you're right, I was misremembering. Against lazy DFAs it was 8~9x, against the raw DFA interpreters (e.g. `try_search_fwd`) it was ~3.5x. And the benchmark I'm looking at is a case that the lazy DFA architecture is unlikely to handle well.

```
Cranelift time (raw DFA): 44.1609ms
raw DFA interpreter time: 150.8189ms
bidirectional DFA interpreter time: 381.7365ms
idiomatic rust regex crate usage time: 403.9569ms
```

I'll try to clean the code up and make it presentable and throw it against rebar. You're right that the benchmark I'm running on is suspiciously narrow; really, it's hacked together from the kind of work I was throwing at the regex library when I started doing this yak shave: https://gist.github.com/wareya/37cd20a4d37cafb89d633d6fa84778e6

> The regex crate already does at least as good as PCRE2's JIT when using lazy DFAs. 

PCRE2's JIT isn't as good as it could/should be, unfortunately. It's probably a limitation of how PCRE2 is put together.

**Comment by wareya** [comment]
For the time being, I ducktaped my DFA JIT into rebar, but there was only one test where the matching process took long enough to counteract the extremely high compilation time, and I had to make a span-instead-of-captures variant of it because the way I designed the JIT doesn't support captures. 95ms vs ~300us compile time, ouch. I might try to find time to look into why it compiles so slowly; lexer DFAs are usually pretty fast to generate, so cranelift might just be getting confused by how many blocks the JIT'd DFA function has and need some babysitting. Or maybe I need to swap out the stdlib hashmaps/etc for non-randomized ones.

In this benchmark it's about 2.5x as fast as the DFA interpreter. (The operative numbers here are 1.66ms and 628.70us.)

The important part of the JIT is `jit_compile_dfa` in `engines/rust/testjit/main.rs`. Its internals are uncommented because I was in a yak shave brain fog when I wrote it.

Also, I didn't double check absolutely everything before pushing this. I don't support multi-pattern matching so I might have to organize the lexer regexes differently or something.

https://github.com/wareya/rebar/tree/testjit

|name                                 |model         |rebar_version         |engine      |engine_version  |err|haystack_len|iters|total|median  |mad     |mean    |stddev  |min     |max     |
|-------------------------------------|--------------|----------------------|------------|----------------|---|------------|-----|-----|--------|--------|--------|--------|--------|--------|
|curated/05-lexer-veryl/single        |count-captures|0.1.0 (rev 49bb2caf1d)|pcre2       |10.47 2025-10-21|   |150600      |44   |4.65s|69.04ms |184.75us|69.51ms |1.04ms  |68.69ms |73.04ms |
|curated/05-lexer-veryl/single        |count-captures|0.1.0 (rev 49bb2caf1d)|pcre2/jit   |10.47 2025-10-21|   |150600      |285  |4.56s|10.47ms |16.40us |10.55ms |454.09us|10.42ms |15.95ms |
|curated/05-lexer-veryl/single        |count-captures|0.1.0 (rev 49bb2caf1d)|rust/regex  |1.12.2          |   |150600      |177  |4.56s|17.02ms |71.40us |17.03ms |204.48us|16.73ms |19.24ms |
|curated/05-lexer-veryl/single-spans  |count-spans   |0.1.0 (rev 49bb2caf1d)|pcre2       |10.47 2025-10-21|   |150600      |50   |4.61s|60.13ms |101.15us|60.14ms |159.32us|59.82ms |60.50ms |
|curated/05-lexer-veryl/single-spans  |count-spans   |0.1.0 (rev 49bb2caf1d)|pcre2/jit   |10.47 2025-10-21|   |150600      |512  |4.54s|5.83ms  |17.20us |5.86ms  |111.09us|5.75ms  |6.86ms  |
|curated/05-lexer-veryl/single-spans  |count-spans   |0.1.0 (rev 49bb2caf1d)|rust/regex  |1.12.2          |   |150600      |1728 |4.55s|1.73ms  |18.00us |1.74ms  |39.26us |1.66ms  |2.11ms  |
|curated/05-lexer-veryl/single-spans  |count-spans   |0.1.0 (rev 49bb2caf1d)|rust/testjit|0.1.0           |   |150600      |4621 |4.65s|647.40us|3.90us  |649.21us|8.43us  |628.70us|772.70us|
|curated/05-lexer-veryl/compile-single|compile       |0.1.0 (rev 49bb2caf1d)|pcre2       |10.47 2025-10-21|   |            |90612|4.61s|29.40us |200.00ns|29.51us |1.08us  |28.40us |56.40us |
|curated/05-lexer-veryl/compile-single|compile       |0.1.0 (rev 49bb2caf1d)|pcre2/jit   |10.47 2025-10-21|   |            |23963|4.56s|116.40us|1.10us  |119.57us|10.74us |112.80us|269.00us|
|curated/05-lexer-veryl/compile-single|compile       |0.1.0 (rev 49bb2caf1d)|rust/regex  |1.12.2          |   |            |7969 |4.56s|348.00us|20.50us |361.96us|45.61us |318.00us|843.10us|
|curated/05-lexer-veryl/compile-single|compile       |0.1.0 (rev 49bb2caf1d)|rust/testjit|0.1.0           |   |            |30   |4.55s|99.77ms |2.54ms  |100.18ms|3.61ms  |94.91ms |111.51ms|
|curated/05-lexer-veryl/multi         |count-spans   |0.1.0 (rev 49bb2caf1d)|rust/regex  |1.12.2          |   |150600      |1440 |4.55s|2.07ms  |18.10us |2.08ms  |65.56us |1.99ms  |3.46ms  |

**Comment by BurntSushi** [comment]
Oh I see. Looking at it more closely, you need to build the full DFA ahead of time. That's mostly a non-starter. I'm not sure any of the regex engines in rebar build a full DFA like that (from a Thompson NFA, that is). The `regex` crate will do so in some circumstances, but only for tiny regexes.

So the benchmark isn't quite right here. The "right" benchmark is to:

1. Add the JIT into `regex-automata` and integrate it into the meta regex.
2. Bake off your meta regex with JIT enabled against a meta regex with [`Config::dfa_size_limit`](https://docs.rs/regex-automata/latest/regex_automata/meta/struct.Config.html#method.dfa_size_limit) _and_ [`Config::dfa_state_limit`](https://docs.rs/regex-automata/latest/regex_automata/meta/struct.Config.html#method.dfa_state_limit) set to `None`.

Then you'd be apples to apples. A likely easier approach is to bake off what you have against just using a `dense::DFA` directly. So you'd want a second benchmark program for that.

If your approach were feasible, then `regex` would use fully compiled DFAs much more.

Also, one note, `regex` doesn't have a "DFA interpreter." A "DFA interpreter" is somewhat of a non-sequitur. With that said, the lazy DFA can devolve to an interpreter. But the standard fully compiled DFA cannot. And the latter is really what you should be comparing against. Otherwise, your approach gets the benefit of assuming that compiling a full DFA is appropriate where as `regex` does not share that assumption.

**Comment by wareya** [comment]
> A likely easier approach is to bake off what you have against just using a dense::DFA directly. So you'd want a second benchmark program for that.

I'll start with this since it only took about 20 minutes to get working, while for the other approach I'm going to have to figure out exactly how the machinery for the meta regex system connects to itself.

The numbers for the dense DFA for this particular benchmark seem worse than what the rust/regex part is doing. I'm going to assume that the full DFA just has much worse cache characteristics or something.. (Dropped the PCRE2 parts because they're not relevant to this particular comparison.)

Pushed the `dfaregex` part of this to the branch I linked earlier, too.

|name                                 |model      |rebar_version         |engine       |engine_version  |err|haystack_len|iters|total|median  |mad     |mean    |stddev  |min     |max     |
|-------------------------------------|-----------|----------------------|-------------|----------------|---|------------|-----|-----|--------|--------|--------|--------|--------|--------|
|curated/05-lexer-veryl/single        |count-captures|0.1.0 (rev 49bb2caf1d)|rust/regex   |1.12.2          |   |150600      |171  |4.54s|17.38ms |240.90us|17.60ms |931.85us|16.94ms |23.81ms |
|curated/05-lexer-veryl/single-spans  |count-spans|0.1.0 (rev 49bb2caf1d)|rust/regex   |1.12.2          |   |150600      |1654 |4.55s|1.77ms  |31.20us |1.81ms  |172.34us|1.65ms  |3.04ms  |
|curated/05-lexer-veryl/single-spans  |count-spans|0.1.0 (rev 49bb2caf1d)|rust/testjit |0.1.0           |   |150600      |4532 |4.65s|653.90us|5.50us  |661.94us|37.72us |630.00us|1.18ms  |
|curated/05-lexer-veryl/single-spans  |count-spans|0.1.0 (rev 49bb2caf1d)|rust/dfaregex|0.1.0           |   |150600      |1597 |4.54s|1.86ms  |19.20us |1.88ms  |99.64us |1.80ms  |3.07ms  |
|curated/05-lexer-veryl/compile-single|compile    |0.1.0 (rev 49bb2caf1d)|rust/regex   |1.12.2          |   |            |8069 |4.54s|346.20us|7.40us  |360.51us|40.43us |331.10us|734.40us|
|curated/05-lexer-veryl/compile-single|compile    |0.1.0 (rev 49bb2caf1d)|rust/testjit |0.1.0           |   |            |28   |4.59s|106.73ms|3.55ms  |107.99ms|5.97ms  |97.81ms |125.79ms|
|curated/05-lexer-veryl/compile-single|compile    |0.1.0 (rev 49bb2caf1d)|rust/dfaregex|0.1.0           |   |            |528  |4.55s|5.61ms  |137.55us|5.68ms  |306.17us|5.24ms  |8.32ms  |
|curated/05-lexer-veryl/multi         |count-spans|0.1.0 (rev 49bb2caf1d)|rust/regex   |1.12.2          |   |150600      |1382 |4.55s|2.12ms  |35.05us |2.17ms  |151.72us|1.99ms  |3.44ms  |


> Also, one note, regex doesn't have a "DFA interpreter." A "DFA interpreter" is somewhat of a non-sequitur. With that said, the lazy DFA can devolve to an interpreter. But the standard fully compiled DFA cannot.

Right. What I'm saying isn't entirely conventional phrasing, but I'm thinking of the DFA state transition graph as being morally equivalent to bytecode or an AST, and operating on it with high-level code (rather than having it be an emergent property of some machine code) as "interpreting" it. I'm thinking of it like how lua (upstream not luajit) is interpreted despite compiling to bytecode, just with something that doesn't look anything like normal interpreter input as the output of the compilation part.

------

There might be a way to lazily JIT only subsections of an NFA into a DFA on demand by tracing NFA execution and compiling only the visited state-set transitions into a DFA, then having that DFA function bail out like "sorry, you have to use the NFA interpreter for this one" if it gets into a state transition that the NFA trace didn't support (and then re-tracing those NFA runs and using them to recompile the DFA with more subsections of the NFA later). But there *should* be a way, I think, to get it so that you don't *need* a fully pre-compiled DFA. I might get experiment with something like this; the main thing I'm worried about is that it might have extremely unreliable performance as new inputs get repeatedly processed.

(Or something vaguely similar, maybe when I finish learning how the lazy DFA works I might have better ideas.)

**Comment by BurntSushi** [comment]
Honestly you might be on to something here! But I probably just don't have the bandwidth to keep up with it right now.

**Comment by wareya** [comment]
No problem! I'll keep doing my thing and come back if the results get more promising, you take care.
