### ISSUE TITLE
Unicode word-boundary matching doesn't follow UAX #29

### ISSUE THREAD

**Issue by rspeer** [rust-lang/regex#332]
The documentation of this crate tells me that `\b` matches a "Unicode word boundary", which it leaves undefined, but which I assume meant a word boundary according to [UAX 29](http://unicode.org/reports/tr29/). But the word boundaries it gives me don't follow UAX 29, and therefore don't match other implementations such as Python's `regex==2017.01.17` package or the Rust `unicode-segmentation` crate.

Here's a test case where the `regex` crate gives inconsistent results on a word containing an apostrophe. The regex `\w(\B\S)*` is supposed to match any word starting with a word character (`\w`) followed by any number of characters that do not cause word breaks (`\B`) and are not whitespace (`\S`):

```rust
    #[test]
    fn test_apostrophe() {
        let word_re: Regex = Regex::new(r"\w(\B\S)*").unwrap();
        let matches = word_re.find_iter("Here's a test");
        let words: Vec<&str> = matches.map(|m| m.as_str()).collect();
        assert_eq!(words, ["Here's", "a", "test"]);
    }
```

When I run this, `regex` considers the apostrophe to be a word boundary:

```
---- tests::test_apostrophe stdout ----
        thread 'tests::test_apostrophe' panicked at 'assertion failed: `(left == right)` (left: `["Here", "s", "a", "test"]`, right: `["Here\'s", "a", "test"]`)', src/lib.rs:182
```

But UAX 29, rule WB6 says that apostrophes that occur between two characters of class AHLetter are not word breaks: http://unicode.org/reports/tr29/#WB6

**Comment by BurntSushi** [comment]
> The documentation of this crate tells me that \b matches a "Unicode word boundary", which it leaves undefined

It's not undefined. The docs say:

```
\b    a Unicode word boundary (\w on one side and \W, \A, or \z on other)
```

where

```
\w     word character (\p{Alphabetic} + \p{M} + \d + \p{Pc} + \p{Join_Control})
```

In other words, this is much closer to "simple word boundaries" [as defined in UTS 18](http://www.unicode.org/reports/tr18/tr18-19.html#Simple_Word_Boundaries).

Implementing UAX 29 (and most of UTS 18 level 2) appear to have major performance implications and therefore would require significant work. Python's regex engine isn't a useful data point *for implementors*, because it uses a completely different approach to matching.

There aren't any plans to pursue UTS 18 level 2 support. I'd be open to someone championing that, but I'm very skeptical that it can be feasibly done. (To be fair, I haven't spent much time thinking about what an implementation path looks like, mostly because it seems so intractable to me.)

**Comment by BurntSushi** [comment]
One thing worth mentioning is that the docs could definitely be a lot better with being more precise about the extent of Unicode support.

**Comment by rspeer** [comment]
Ah, I see.

Indeed, I notice that if I use the `unicode-segmentation` crate, it slows down segmentation to merely twice the speed of Python's implementation, which is quite a performance cost. I had thought that the slowdown came from my code, which is why I wanted to try an alternative implementation using `regex`, but the slowdown seems to be inherent.

So I understand the decision you made. It's a bummer not to be able to match words with apostrophes in them, though.
