### ISSUE TITLE
Implement (at least part of) UTS#18 RL1.3 - Operators in character sets

### ISSUE THREAD

**Issue by trishume** [rust-lang/regex#341]
I'm working on a syntax highlighting engine in Rust that requires an Oniguruma-compatible regex engine. I'm trying to port it from the `onig` crate to [fancy-regex](https://github.com/google/fancy-regex), but there's some features it doesn't support yet (see https://github.com/trishume/syntect/pull/34).

One of these features is the `&&` operator and nesting in character sets, for example `[a-w&&[^c-g]z]`. I was thinking this would be added to fancy-regex but @robinst pointed out [this comment](https://github.com/rust-lang/regex/blob/52fdae7169ec619530985a019184319ac4bbee5a/regex-syntax/src/lib.rs#L1408-L1410) which suggests that you plan for them to be in the `regex` crate.

It would be nice if the `regex` crate supported [UTS#18 RL1.3](http://www.unicode.org/reports/tr18/tr18-19.html#Subtraction_and_Intersection) in full, but the `&&` operator and nesting are all that Oniguruma-compatibility of fancy-regex requires.

I imagine this would take some changes to `regex-syntax` and then a pass to convert the fancy character sets down to basic character sets. I haven't thought enough about it to know if there are any unicode-related issues that might make this more complex, perhaps by making a tiny fancy character set compile to an enormous basic character set.

@BurntSushi do you have any insight on how difficult you think this would be to add for a contributor not familiar with the internals of `regex`?

**Comment by BurntSushi** [comment]
> do you have any insight on how difficult you think this would be to add for a contributor not familiar with the internals of regex?

My belief is that the change would be limited to `regex-syntax` and shouldn't bleed into anything else. If that's true, then that makes this task "medium" instead of "hard" because it reduces the amount of code you need to be familiar with. In fact, I don't think it even requires changing the existing AST.

I'd still consider this to be a tricky task. I think the parser itself seems a bit complex (the char class parser is *already* complex, so spending some time trying to make that nicer is probably a worthwhile investment). I also think there could be some issue with computing the various set operations because Unicode makes the sets quite large. For example, `[^c-g]` is *every Unicode codepoint* other than `c-g`.

In general, parsing takes an insignificant time in regex construction compared to the time it takes to compile the regex. I would hope that even with this change, it would stay that way. Maybe set operations on Unicode sets aren't as bad as I think, but if they wind up slowing down parsing a lot, then we might need to be more clever. And that makes this task "medium" instead of "easyish."

At a higher level, I do have plans to rewrite the parser from scratch (again), but I have no idea when that will happen and you shouldn't plan around it.

**Comment by BurntSushi** [comment]
Also, I would expect test coverage to remain excellent. Every single branch should be covered by a test. (I believe this is true today.)

**Comment by trishume** [comment]
@BurntSushi awesome, thanks for the insight.

**Comment by BurntSushi** [comment]
Oh and I'd be happy to answer questions and mentor anyone who works on this. I'm on the usual IRC channels, typically 4-8pm EST and sporadically on the weekends. Email also works well, which I'm on around the clock.

**Comment by robinst** [comment]
I started looking into this after I made the comment on the syntect issue :). I too think it can be entirely implemented in `regex-syntax`. Looks like the work is roughly:

1. Make `parse_class` handle nested classes
2. Make it handle `&&`
3. Add a `intersect` method to `CharClass`

We should probably focus on `&&` as a first step, I'm not sure the other operations are in wide use (e.g. Oniguruma only has `&&`).

The first change I have is extracting a `parse_class_escape` method to make `parse_class` a bit smaller. Would you prefer individual pull requests for steps along the way, or a bigger one with multiple commits at the end?

**Comment by BurntSushi** [comment]
I think a single commit with everything would be best. If you wanted to
open a PR for earlier feedback that's fine, so long as it gets squashed in
the end. :-)

**Comment by robinst** [comment]
Quick status update: I have support for nested classes and intersection using `&&`, currently writing all the tests to make sure all things are covered.

**Comment by robinst** [comment]
Pull request for nested classes and intersection: https://github.com/rust-lang/regex/pull/346
