### ISSUE TITLE
Regex match disagreement with Python, Perl, egrep(1)

### ISSUE THREAD

**Issue by dmo2118** [rust-lang/regex#347]
A short Python 3 program:

```python
import re
print(re.match(r'^(aba|a)c*(b|$)','abaca').groups())
```

gives `('a', 'b')`

---

In Perl:
```perl
"abaca" =~ /^(aba|a)c*(b|$)/;
print "$1, $2\n";
```
...which gives `a, b`

---

And with GNU `egrep`:
```sh
$ echo abaca | egrep --color '^(aba|a)c*(b|$)'
```
<code>**ab**aca</code>

---

And finally, regex in Rust:
```rust
extern crate regex;

fn main() {
    println!("{:?}", regex::Regex::new("^(aba|a)c*(b|$)")
    	.unwrap().captures("abaca"));
}
```

This doesn't seem right, though.
0.2.1 gives: `Some(Captures({0: Some("aba"), 1: Some("aba"), 2: Some("")}))`
And the master branch, currently @ `204e4094`: `Some(Captures({0: Some("abac"), 1: Some("aba"), 2: Some("")}))`

**Comment by dmo2118** [comment]
Looks like this changed for version 0.1.69, and 0.1.68 was OK. Given:
```rust
extern crate regex;

fn main() {
    for capture in regex::Regex::new("^(aba|a)c*(b|$)").unwrap()
        .captures("abaca").unwrap().iter() {
        print!("{:?} ", capture);
    }
    println!();
}
```

0.1.68: `Some("ab") Some("a") Some("b")`
0.1.69: `Some("aba") Some("aba") Some("")`

**Comment by BurntSushi** [comment]
Yeah, this is a tricky one to fix. Basically, there is an optimization where by after running the DFA, we run the NFA to resolve capture locations. But when we run the NFA, we restrict the search text to only the region of text that was matched by the DFA. This ends up being wrong because the NFA engine will then match things like `$` because it will falsely believe it is at the end of the search text. There are some "heuristics" in the current implementation that extend the search text a few bytes past the end of the match, but that doesn't work in the general case.

In this case, the DFA will (correctly) determine the match to be `ab`, but then it will pass `abac` to the NFA to resolve captures. The NFA will then (correctly, from its perspective) determine the match to be `abac` since the `$` in `(b|$)` will wind up matching.

To fix this, we either need to fix the NFA engines or revert the optimization.

**Comment by dmo2118** [comment]
Building against the latest regex v0.2.10:

```rust
extern crate regex;

fn main() {
	for capture in regex::Regex::new("^(aba|a)c*(b|$)").unwrap()
		.captures("abaca").unwrap().iter() {
		print!("{:?} ", capture.map(|x| { x.as_str() }));
	}
	println!();
}
```

...now gives `Some("ab") Some("a") Some("b")`, which is what I need. And for what it's worth, the bigger, uglier regex that `(aba|a)c*(b|$)` is based off of also passes its test cases (at only ~5 KB/sec under a debug build, but it passes).

I don't know if the aforementioned NFA issue is still present, but my original issue is resolved. Closing.
