### ISSUE TITLE
Question about \p script matching

### ISSUE THREAD

**Issue by elirnm** [rust-lang/regex#351]
The docs just say that `\p{Blah}` matches "Unicode character class (general category or script)." I took this to mean that it would match against anything listed under scripts on http://www.unicode.org/charts/, but there's a number of those that it doesn't recognize, including some ones I would have expected by default such as `CJK` (or `CJK Unified Ideographs`).

Is there some documentation of which scripts are supported in `\p` matching?

**Comment by BurntSushi** [comment]
> Is there some documentation of which scripts are supported in \p matching?

The documentation is intended to be provided by Unicode.

More specifically, the scripts available in this crate are generated directly from this file: http://www.unicode.org/Public/UNIDATA/Scripts.txt

I don't know what the correspondence is between the link you provided and the `Scripts.txt` file. :-/ It seems like there is a lot of overlap, and maybe there is just a naming mismatch. For example, `Scripts.txt` contains a `Han` script, but I don't see a granular breakdown of CJK as listed in your chart page.

**Comment by elirnm** [comment]
Ok, thanks.

**Comment by BurntSushi** [comment]
@elirnm Well that seems... a little annoying. Maybe we should provide the full list in the regex docs somewhere if Unicode isn't going to make it more accessible themselves.

**Comment by elirnm** [comment]
Or at least provide a link to that scripts file so users can get some idea of what's supported?

**Comment by saona-raimundo** [comment]
Hi! 
I would like to revive this thread (I can open a new one if needed).
I was having trouble understanding the extent of the \p notation.
Here are my thoughts.

- The [crate-level documentation](https://docs.rs/regex/latest/regex/#unicode) has a list. The first element links to [UNICODE.md](https://github.com/rust-lang/regex/blob/master/UNICODE.md#rl12-properties), while the second to last element talks about the `\p` notation. 
Since elements of a list are at the same level, I suggest bringing UNICODE.md before the whole list.

- The documentation in [UNICODE.md](https://github.com/rust-lang/regex/blob/master/UNICODE.md#rl12-properties) includes a list of "all properties supported by the regex crate", but the list is missing "Greek", which is part of the examples in the documentation.
Is the list not updated? would you like the list to be generated from the implementation?

**Comment by BurntSushi** [comment]
@saona-raimundo While your comment is tangentially related, please don't bump issues closed years ago. If you have questions, you should [open a new Discussion](https://github.com/rust-lang/regex/discussions). If you click the "new issue" button, there is even an explicit category for "ask a question":

![ask](https://github.com/rust-lang/regex/assets/456674/81afe487-6755-4690-8747-c332708b8042)

I copied your second bullet point into a distinct question here and tried to answer it: https://github.com/rust-lang/regex/discussions/1144

I don't understand your first bullet point. Please open a new discussion question and fill out the question more.
