### ISSUE TITLE
Implement `is_match_start` and `is_match_end` methods

### ISSUE THREAD

**Issue by sortiz4** [rust-lang/regex#366]
I have a few patterns that I'd like to quickly match against the beginning and end of a buffer before searching the middle. My current workaround involves compiling three separate regular expressions for each pattern and wrapping them in a struct. It's not great. Adding `*_start` and `*_end` methods (where applicable) would offer much greater flexibility.

Also, what's the reasoning behind making `Match::new()` private? I tried implementing a trait for `Regex` that returns an optional `Match` and I had to copy, paste, and rename the struct.

**Comment by BurntSushi** [comment]
> I have a few patterns that I'd like to quickly match against the beginning and end of a buffer before searching the middle.

Could you give an example?

> My current workaround involves compiling three separate regular expressions for each pattern and wrapping them in a struct. It sucks.

Why do you think this is inadequate? It seems perfectly reasonable to me. Given the details you've given, it also seems like you could get away with only two regexes, no? 

> Adding *_start and *_end methods (where applicable) would offer much greater flexibility.

Do you think your use case is so common that ~tripling the size of the current matching API is actually worth it?

> Also, what's the reasoning behind making Match::new() private?

I'd rather ask, "what's the reasoning behind wanting `Match::new()` to be public?" If `Match::new` is public, then we limit our future ability to change its representation. Although, it does seem likely that `Match::new(substring, start, end)` should always be supportable.

But if `Match::new` is public, does that mean we should also add `set` methods on a `Match` so that it can be modified in place? (Which, depending on how the optimizer is feeling, might be quicker than creating a new `Match` value.)

**Comment by sortiz4** [comment]
I'm working on a lexer with about 70+ patterns. I say that my solution sucks because I'm wrapping each pattern in `^()` and `()$` and compiling all three which *seems* inefficient given the minor differences (and not knowing what the added cost of implementing the suggested methods would be). I'm only using the `^()` pattern right now, but I'd like to leave room for some additional use cases. I only suggested the `*_start` and `*_end` for the sake of completeness, but I do think that the current API is lacking (which is why I needed access to `Match::new`). I can't say how common these use cases would be, but I've found the Python `re` module `search`, `match`, and `fullmatch` methods for general patterns to be *very* helpful and it's something I'd like to see in this crate.

**Comment by BurntSushi** [comment]
My rebuttal is that I've seen countless people confused with Python's `re` module, specifically over the difference between `search` and `match`. In general, I think small, orthogonal and hard-to-misuse APIs are extremely undervalued.

From my perspective, your current implementation strategy seems reasonable to me, but it does seem wise to leave this ticket open so that others might voice their concerns.

**Comment by RReverser** [comment]
@BurntSushi I have quite similar issue, but instead of just booleans, could use something similar to ES6 "sticky regex".

Specifically, I'd like a version of `find_iter` that matches regexes only if they match consecutively, and not anywhere in the string since the last seen position. Right now the only way to do this seems to have `^` on the beginning of each regex and run a manual loop where you do `.find` and then cut the string slice past the matched position. This is quite cumbersome and a convenient alternative would be appreciated.

**Comment by BurntSushi** [comment]
@RReverser That sounds like a completely different piece of functionality than what this issue is about? Could you please open a new issue and include some concrete examples where you'd like to use it?

**Comment by RReverser** [comment]
@BurntSushi I was just trying to find if a relevant issue exists, this (`is_match_start` / `is_match_end`) sounded like the closest one, apologies if not appropriate.
