### ISSUE TITLE
Capturing groups from multi line string

### ISSUE THREAD

**Issue by opensourcegeek** [rust-lang/regex#372]
I've some string response which contains mac addresses separated by new line, 

```
UCD-SNMP-MIB::extNames.200.101.3 = STRING: AB:90:0D:E1:12:13
UCD-SNMP-MIB::extNames.200.101.3 = STRING: AB:90:0D:E1:12:13
UCD-SNMP-MIB::extNames.200.101.3 = STRING: AB:90:0D:E1:12:13
```

I can use RegexBuilder to turn multi_line on, but when I try to capture groups, I still get only captured group from the first line 

```rust
#[test]
    fn test_get_mac_address_positive() -> () {
        let sample = "UCD-SNMP-MIB::extNames.200.101.3 = STRING: AB:90:0D:E1:12:13
UCD-SNMP-MIB::extNames.200.101.3 = STRING: AB:90:0D:E1:12:13
UCD-SNMP-MIB::extNames.200.101.3 = STRING: AB:90:0D:E1:12:13";
        
        let re = RegexBuilder::new("([0-9A-F]{2}[:|-][0-9A-F]{2}[:|-][0-9A-F]{2}[:|-][0-9A-F]{2}[:|-][0-9A-F]{2}[:|-][0-9A-F]{2})")
                .multi_line(true)
                .build()
                .unwrap();
        let caps = re.captures(sample);
        println!("{:?}", caps);
    }
```
```
running 1 test
Some(Captures({0: Some("AB:90:0D:E1:12:13"), 1: Some("AB:90:0D:E1:12:13")}))
test snmp_gatherer::tests::test_mac_captures_regex__positive ... ok
```
I'm not sure if I should break the string by new line before checking for mac address or if this capturing should work. I tried here https://regex101.com/r/bPIFQU/1/ which seems to match more than one line. Any help would be appreciated.

**Comment by BurntSushi** [comment]
@opensourcegeek The [`captures` method](https://docs.rs/regex/0.2.2/regex/struct.Regex.html#method.captures) returns a *single* match. The [`captures_iter` method](https://docs.rs/regex/0.2.2/regex/struct.Regex.html#method.captures_iter) returns an iterator of matches. That is, since you're using `captures`, you've limited yourself to the first match in the text. If you want all the matches, then you necessarily need some kind of loop over all of the matches. Finally, you don't need "multi line" for this. As the [docs say](https://docs.rs/regex/0.2.2/regex/#grouping-and-flags), multi-line mode is for causing `^` and `$` to match on `\n` boundaries, but your regex doesn't use `^` or `$` at all, so enabling multi-line mode has no effect.

Here is a complete program that I think does what you want:

```rust
extern crate regex;

use regex::Regex;

fn main() {
   let sample = "UCD-SNMP-MIB::extNames.200.101.3 = STRING: AB:90:0D:E1:12:13
UCD-SNMP-MIB::extNames.200.101.3 = STRING: AB:90:0D:E1:12:13
UCD-SNMP-MIB::extNames.200.101.3 = STRING: AB:90:0D:E1:12:13";

    let re = Regex::new("([0-9A-F]{2}[:|-][0-9A-F]{2}[:|-][0-9A-F]{2}[:|-][0-9A-F]{2}[:|-][0-9A-F]{2}[:|-][0-9A-F]{2})").unwrap();
    for caps in re.captures_iter(sample) {
        println!("{:?}", caps);
    }
}
```

I am very interested to hear how I can improve this situation. What would have you liked to see in the documentation that would have cleared this up for you?

**Comment by opensourcegeek** [comment]
I think it's my fault for not reading the docs properly and also I'm not a regex expert.

I saw captures_iter and thought it is used for going through multiple capture groups in the same line as example showed, but didn't realise I can use one capture group across multiple lines as well with that method. Some more examples would definitely be very useful with new lines. Also seeing multi_line method in regex builder I thought enabling it would fix it. I didn't lookup what `m` switch stands for either (again my fault). 

Another thing is, when I used negative look ahead I just got cannot be parsed msg as error. It would be nicer if it specifically mentioned why the regex isn't valid. I had to look into docs to see why it didn't compile regex I gave. 

I think the documentation is already pretty good and I appreciate the effort you're taking to make the experience of users of this API even better. Also thanks for answering my question.

**Comment by BurntSushi** [comment]
I think one easy improvement we could make here is to improve the documentation on the [`RegexBuilder` methods](https://docs.rs/regex/0.2.2/regex/struct.RegexBuilder.html). For example, instead of just saying "Set the value for the multi-line matching (`m`) flag." for the `multi_line` method, we should probably add another sentence that describes what the `m` flag actually means. Similarly for the other methods that twiddle regex flags. The meaning of each flag can be found here: https://docs.rs/regex/0.2.2/regex/#grouping-and-flags
