### ISSUE TITLE
backreference tries to match impossible capture names.

### ISSUE THREAD

**Issue by fulara** [rust-lang/regex#399]
Sorry about confusing topic - below fragment should be self explanatory.
```
extern crate regex;

use regex::Regex;

fn main() {
   let r = Regex::new("(a)").unwrap();
   let result = r.replace_all("xax", "$1Q").into_owned();
   assert_eq!("xaQx", result); // fails, result is xax
}
```
I think the replace should see the capture name $1 since Q is not a number. Especially that you are not allowed to create a capture names starting with numbers see this error message:
```
Capture names must consist of [_a-zA-Z0-9] and are not allowed to start with with a number.
```
This works as I expected in sed and notepad++.

**Comment by BurntSushi** [comment]
This is expected behavior. In fact, this particular case is even called out explicitly in the documentation: https://docs.rs/regex/0.2.2/regex/struct.Captures.html#method.expand --- It even tells you how to fix it. :-)

If you're not reporting this as a bug but instead a feature request, then I think I'd disagree. I'd rather stick to simple rules.

**Comment by fulara** [comment]
Okay. :) 
I've missed this in the doc.
I've created a small test which would tell someone like me about that usage, you can merge that if you want. :)

I raised it as a bug.
