### ISSUE TITLE
performance optimisation of EOL matching using ReverseSearcher

### ISSUE THREAD

**Issue by benaryorg** [rust-lang/regex#463]
Today I talked to people about the performance of matching something at the end of a line.
The idea popped into my head while matching something along that:

```text
up foo 123
down bar 124
up baz 125
```

I'd like to match for `^up` which is really straight forward.
Then however I'd like to have the remaining numbers, which brings us to the actually important part.
Matching the number requires to match `[0-9]+$` which basically skims through the whole text without the need to.
While the first regex looks for `\n` and then only ever looks at the first few characters, the latter one tries to match every single character in the string, and when it finds a number not at the end, matches it, only to discard it when not finding `\n` after it.

I don't know the internals of the regex engine, but I feel like it should be much faster to reverse the string (or tell the engine to match each line backwards internally) and match using `^[0-9]+` then.
Reversing however requires memory allocations or at least memory writes, which is undesirable when it comes to performance.
Matching on an Iterator (#425) would be awesome here as it would allow me to get the reversed iterator from a DoubleEndedIterator (as String should be able to yield).
Maybe this is also possible with Read (which String implements too).

We could prevent this kind of overhead though when the engine was capable of inverting all of it's index accesses so that it still works through the string the same way, but backwards.

The code for benchmarking this would be something like [this piece of code](https://gist.github.com/benaryorg/c90d1771506cdb571dc0323a70007273), however I'm iterating through 4GiB of [text](http://www.catipsum.com/) in less than three seconds, so it'd need subsecond resolution.
Note that it currently fails with that error message (hence the issue):

```text
error[E0277]: the trait bound `regex::pattern::RegexSearcher<'_, '_>: std::str::pattern::ReverseSearcher<'_>` is not satisfied
  --> src/main.rs:50:22
   |
50 |             .filter(|str| str.rfind(&regex_front).is_some())
   |                               ^^^^^ the trait `std::str::pattern::ReverseSearcher<'_>` is not implemented for `regex::pattern::RegexSearcher<'_, '_>`

error: aborting due to previous error
```

Maybe I'm entirely wrong and you can clarify how this particular engine does it's thing though ;-)

**Comment by ethanpailes** [comment]
I think the DFA already does this (https://github.com/rust-lang/regex/blob/master/src/exec.rs#L680). It can be detected at compile time, so there is no extra method that you as the user have to call. Yay, small API surface!

**Comment by oseiberts11** [comment]
How do you think that you find the end of the line? That often requires looking at all the bytes in the line anyway (unless you optimize this somehow by storing your lines cleverly and re-using information from one line to the next). DFAs are really fast [if implemented properly, see below] so just finding the end of the line isn't necessarily much faster than matching the regex.

Here is an article by Ken Thompson from 1968 about translating a DFA/regex directly to machine language: https://www.fing.edu.uy/inco/cursos/intropln/material/p419-thompson.pdf
This is one of my advocate-of-the-devil arguments that "there hasn't really been anything new in computer science since the 1970's" :-)
Here is a more recent summary and overview (it refers to Thompson of course) https://swtch.com/~rsc/regexp/regexp1.html

**Comment by BurntSushi** [comment]
@benaryorg I don't really know what to make of this issue. It is all over the place. Are you asking a question about a potential optimization? Are you asking for new APIs? Are you asking how to solve a particular kind of a problem?

>  DFAs are really fast [if implemented properly, see below] so just finding the end of the line isn't necessarily much faster than matching the regex.

This is definitively false, and is exactly the motivation for why literal optimizations play such a large role in this particular regex library.

**Comment by oseiberts11** [comment]
I say "necessarily" which is a weasel word that gets me out of this; yes, it depends on the implementation of the regex.

**Comment by benaryorg** [comment]
@BurntSushi 
> I don't really know what to make of this issue.

True, I haven't been very specific, I hope the new title reflects that.
The question I had, was whether implementing `ReverseSearcher` would provide any performance gain as opposed to using a pattern matching EOL.

If @ethanpailes is right with the optimisation and it is already as performant as possible, then this issue is basically solved.
Otherwise I'd like to get some more information on how to cope with EOL matching and get the best performance, and if necessary introduce API changes to allow reverse matching of some sort (you're free to Won't Fix such a change of course).

**Comment by BurntSushi** [comment]
@benaryorg If a regex is anchored at the end, then it will do a reverse search: https://github.com/rust-lang/regex/blob/2b1fc2772dc4d99ad732a43751fb5627f327abc8/src/exec.rs#L1182-L1186

This is somewhat orthogonal to EOL matching, and requires more sophistication in literal optimizations to work. To a large extent, this is already [implemented for arbitrary literal suffixes (including the reverse search)](https://github.com/rust-lang/regex/blob/2b1fc2772dc4d99ad732a43751fb5627f327abc8/src/exec.rs#L1199-L1219). The part that is missing is the adaptation for `(?m)$` (as distinct from just `$`, which is handled by the aforementioned anchored reverse search). The reason why this part is missing is because the code for handling literals isn't smart enough. It is part of my long term plans to overhaul most of the regex crate, and a large component of that is improving the handling of literals to make them smarter and more flexible, including handling the `(?m)^` and `(?m)$` cases.

The time frame on that work is best measured in years.
