### ISSUE TITLE
Exit with error if no correct $name found

### ISSUE THREAD

**Issue by yory8** [rust-lang/regex#485]
Currently, if I try to replace `\d_\w` with `${2}_${1}` I get the string `_`, because the crate doesn't abort with an error. 

Though this is thoroughly documented, I find it a surprising choice, coming from python where doing that would exit with `error: invalid group reference`. 

IMHO Python's approach seems more useful, as it's much more probable that I forgot the parenthesis (it just bit me) rather than I meant `${2}` as a literal string.

What do you think?

**Comment by BurntSushi** [comment]
I certainly considered this, and honestly, either approach is reasonable. I don't believe it's all that surprising; it has precedent elsewhere. Here are the key points as I see it:

* Doing this requires either a breaking change with a semver bump or the addition of a new suite of replacement methods that return errors. This reasoning alone is enough for me to say "no" to this request IMO. That is, even if I agreed with you that this was a wart, I would say that we should make peace with it.
* The replacement routines would need to return a `Result<Cow<str>, ReplacementError>` instead of the much simpler `Cow<str>` that it returns today. This will also force callers to handle the error. In most cases, I'd expect callers to insert an `unwrap()` since the replacement string is likely written by the programmer.
* Baking error checking into the replacement code could have performance implications. Admittedly, they are probably quite small and amenable to optimization.
* The specific bug you cite seems like something that would be very quickly caught. That is, it isn't a bug that manifests itself in a corner case. Pretty much every replacement executed will result in an unexpected answer, which means that even a trivial unit test will catch this. (This isn't to wave away the problem completely, but when evaluating requests such as yours, we must at least attempt to weight its magnitude.)

**Comment by yory8** [comment]
Thank'you for the detailed follow-up. 
My use case is problematic because the regex (both search and replace) is submitted by users  (like submitting the search pattern in your ripgrep), not embedded in the program itself, so testing doesn't help.
I understand your stance, anyway, it's definitely quite a disruptive change.

**Comment by BurntSushi** [comment]
@yory8 I see. You might just consider attempting to parse the replacement string and doing the error checking yourself. You can probably copy the parser straight out of the regex crate.

I'm going to close this out because I think we should stick with what we have.
