### ISSUE TITLE
Segmentation fault: 11 error on OSX in release mode

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/regex#489]
Works in debug mode but fails in release mode.

OSX 10.11.5

Tested with:

- rustc 1.26.2 (594fb253c 2018-06-01)
- rustc 1.28.0-nightly (967c1f3be 2018-06-15)

```rust
extern crate regex;

use regex::Regex;

fn main() {
    let regex = Regex::new("^1$").unwrap();
    println!("{}", regex.is_match("1"));
}
```

**Comment by BurntSushi** [comment]
I've seen enough of the OSX TLS bug that this is probably a duplicate: https://github.com/rustwasm/wasm-bindgen/issues/186

I'd be happy to re-open this if more evidence reveals that it's a different bug.

**Comment by bvssvni** [comment]
Wasn't trying to build wasm?

**Comment by BurntSushi** [comment]
@bvssvni The root cause comes from regex: https://github.com/rustwasm/wasm-bindgen/issues/186#issuecomment-386843744

I've seen this issue crop up in other areas as well. See also:

* https://github.com/rust-lang/rust/issues/50586
* https://github.com/rust-lang/rust/issues/48866
* https://github.com/rust-lang/rust/issues/50867
