### ISSUE TITLE
Publish unicode-tables as a separate crate?

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/regex#496]
Hi, I'm using regex and need access to the unicode tables. I don't really want to duplicate those data. Any chance it can be published as a separate crate somehow?

**Comment by BurntSushi** [comment]
What problem are you trying to solve?

**Comment by crlf0710** [comment]
Hi, i can obviously copy all those generated files from `regex` and include them in my crate. However as i'm also using `regex` too so these data actually exists twice in the generated binary (correct me if i'm wrong). If it is a single crate then there's one single dependency on it, so these data won't be duplicated.

**Comment by BurntSushi** [comment]
I'll ask again: could you please state the high level problem you're to solve? Making Unicode tables public is a means to an end. *Why* do you want access to those tables? What do you want to do with them?

**Comment by crlf0710** [comment]
Sure, I want to check whether a code point lives in a specific general category, and whether it has id_start/id_continue,  xid_start/xid_continue properties. I'm doing some parsing and these properties are required from the spec.

**Comment by BurntSushi** [comment]
You might consider just using a regex to do that.

I personally have mixed feelings on this. Obviously, the biggest advantage to providing the tables is that we reduce the number of copies, and therefore, the binary size, since these tables can be somewhat significant in size. I suspect this is the only advantage since the `ucd-generate` tool should be more than capable of making it easy to build these tables yourself.

With that said... There are a myriad of problems:

* The tables in the regex crate are specifically generated for the specific use case of the regex crate. Notably, the regex crate does not require blindingly fast lookups since the tables aren't used at a match time and only at compile time. (For the most part.) Therefore, the tables don't have universal applicability and may not fit everyone's use case.
* There is non-trivial maintenance required in exporting the tables. It needs documentation and a description of how each table is built and how to use them. This new crate will also attract new kinds of bug reports and PRs that I'm not sure I want to be responsible for.

cc @SimonSapin What do you think about this? Do you have any kind of vision here? My thinking is that will be pretty hard to share the internal Unicode tables between a decentralized set of crates without a strong coherent vision on how it all fits together. But I might be missing something!

**Comment by SimonSapin** [comment]
I think it’s really good that `ucd-generate` or something like it exists to unify the way Unicode data is parsed and processed in the Rust ecosystem, rather than having everyone forking and tweaking various copies of the same Python script.

That said I do not particularly have a vision or plans further than that. It’s hard to come up with something that’ll work for every case we haven’t yet thought of. You mentioned lookup speed, which is likely a classic space v.s. time trade-off. I suspect this is one of a number of axes where different users might want to make different choices.

**Comment by crlf0710** [comment]
Thanks for the explanation and vision! I'm going to close to this issue.
