### ISSUE TITLE
make case insensitive comparisons better

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang/regex#55]
We should switch from equality comparison on the first character returned by `{upper,lower}case` iterators to "does this character match *any* character in the `{upper,lower}case` iterator."

**Comment by SimonSapin** [comment]
For what it’s worth, [in ES6](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-canonicalize-abstract-operation), a regex with both `i` (case-insensitive) and `u` (better Unicode support) flags uses *common* and *simple* mappings from Unicode’s [`CaseFolding.txt`](http://www.unicode.org/Public/UNIDATA/CaseFolding.txt). These mapping preserve the number of code points. Using *full* mapping instead of *simple* gives “more correct” results, but it can grow the number of code points.

Either way, case folding (for caseless matching) is not the quite as either lower-case or upper-case.

I didn’t manage to find a spec for what Perl does exactly (though I didn’t search very hard). The Python documentation is equally unhelpful.
