### ISSUE TITLE
Group captured multiple time in one "capture"

### ISSUE THREAD

**Issue by HarrisonMc555** [rust-lang/regex#558]
There are some situations in which the easiest way to express a regular expression is to have a group occur possibly multiple times. Sometimes, you may want to extract what that group captured. However, I could not find a way to extract those multiple captures out of the resulting `Captures` struct.

For example:

`(\w)(-\w+)*`

Matching this pattern against

`aaa-bbb-ccc`

Would produce both `"aaa"` (for `caps.get(1)`) and `["-bbb", "-ccc"]` (for `caps.get(2)`).

I would like to get _all_ matches of the second group. Is there a way to do this?

I'm aware of #432, but I don't think it's the same question. If it is, then that issue wasn't worded very clearly.

**Comment by BurntSushi** [comment]
Beyond captures_iter, no, there is nothing that let's you do this and there are no plans to support it. I'm not aware of any regex engine that provides this. You'll need to rework your regex or use something else for parsing.

**Comment by TheCycoONE** [comment]
According to https://stackoverflow.com/questions/65457019/get-all-strings-matched-by-a-nested-capture-group-in-rust both .NET and PyPi support this - if that does anything at all to sway your opinion.

**Comment by BurntSushi** [comment]
PyPI is the Python package repository. I assume you're referring to the `regex` package on PyPI. That package supports everything under the sun. Perhaps the most featureful regex enginw there is.

That other regex engines support this doesn't really sway me. What would sway me is if there was a simple API and a simple implementation for this feature that is consistent with the crate's design.

More compelling use cases would also be needed. My expectation is that most cases could be tweaked just a bit to do what you want.

**Comment by AZMCode** [comment]
The API changes wouldn't need to be too substantial, just returning a Vec<Match<_>>  instead of an Option<Match<_>> in the methods for retrieving capture groups would be sufficient for this.

I understand "it helps in parsing" is not the biggest motivation to make a feature in a regex engine happen, but consider the following example:

Someone wishes to parse a string consisting entirely of lowercase letters and numbers, yet wishes to capture the letters and the numbers separately, and wishes to not match anything at all if there are uppercase characters.

Given this feature request, the task would be as simple as parsing the string with the following regex:
`^((?<letters>[a-z]+)|(?<numbers>[0-9]))+$`
Retrieving a list of matches for the letters, and a list of matches for the numbers.

Doing that logic without this feature requires not only reworking the regex to `(?<letters>[a-z]+)|(?<numbers>[0-9]), but adding extra external logic to ensure there are no extraneous characters anywhere in the string, and using the captures_iter method, and collecting the vector of resulting matches. Not all regexes would allow for such a reworking though.

The particular reason I'm here is because I need to replace all matches of a capture group with another thing, which also isn't possible using the current design of the crate unless I do an ungodly amount of backreferences and do a separate regex replace for each capture group I want replaced.

All this to say, +1 to the issue submitter, and I'd love to see this feature added.

**Comment by BurntSushi** [comment]
That API is insufficient. Aside from probably wanting to be a `&[Match]`, the main issue is that it implies all matches of every capture search are recorded. That can be a huge additional cost in some cases, inappropriately so. Thus, capturing all matches can't always be done. This seems to imply adding more search APIs that extract the additional information or some kind of regex builder option that enables it. Either way, there is non-trivial API design.

But that's only 1 part of the 2 necessary (and perhaps not sufficient) parts. The other part is the implementation. This isn't a case where the internals have the data you want and it just isn't exposed. This requires changing how one or more of the regex engines actually work. And defining semantics for it.

I think this is the point where you either use multiple regexes or don't use regexes at all. Personally, I find your example parsing task to be quite odd. I'm sure your real use case is more interesting, but my request for motiviating examples still stands. (And part of that is making an argument that this is a common enough need to justify the additional API and implementation complexity. My suspicion is that this bar is unlikely to be cleared.)
