### ISSUE TITLE
Suggest that ++ be a syntax error

### ISSUE THREAD

**Issue by davisjam** [rust-lang/regex#559]
At the moment, AFAICT Rust handles `a++` the same as `a+`. This notation is usually used to request possessive/atomic behavior, and I think a syntax error would be preferable to a silent retreat.
- JavaScript and Python throw a syntax error
- Possibly, Rust interprets `a++` as "`a+` with a `+`". If so this is confusing.

**Comment by BurntSushi** [comment]
This is a breaking change, so at the very minimum, this cannot be done until a `regex 2.0.0` release. A 2.0 release is not on my mind at all, and this issue alone---even if I agreed with it---is not enough to motivate a 2.0 release. For that reason, I'm going to close this but mark it with a label in case we want to revisit it.

I'd like to try to provide a counterpoint. In general, I'm not completely convinced that this should be an error. You really want the ability to be able to say things like `(foo(bar)+)+`, which has a similar effect of applying a repetition operator on top of a repetition operator. To me, allowing `a++` is consistent with that. Moreover, given that the `a++` syntax is specifically designed to limit backtracking and this library makes it clear that it is not a backtracking library, I feel like that might be good enough.

With that said, I do generally agree with your point. It's a small bump but it might indeed make sense to _specifically_ prohibit syntax that is otherwise treated as a possessive quantifier in other regex engines.

**Comment by davisjam** [comment]
> You really want the ability to be able to say things like (foo(bar)+)+, which has a similar effect of applying a repetition operator on top of a repetition operator. To me, allowing a++ is consistent with that.

I agree that `(foo(bar)+)+` is a thing that people should be able to do, but there they are repeating a group which happens to itself contain a quantifier. It is less obvious that`a++` is equivalent to `(a+)+`, since there is a "syntax collision" between that interpretation and the use of `a++` to denote a possessive quantifier. The current behavior implies to users that they are getting a feature that Rust does not actually support.

I also agree that a 2.0 release would be a good place for this.

@BurntSushi On a related note, I recently completed a research project that compares multiple regex engines. Would you be interested in reading the manuscript? I would certainly appreciate your feedback.

**Comment by BurntSushi** [comment]
> On a related note, I recently completed a research project that compares multiple regex engines. Would you be interested in reading the manuscript?

Sure! Just shoot me an email. :-)

**Comment by Canop** [comment]
Does this issue also cover the case of `**` (which is a syntax errors in all other engines I know including Re2) ?

Is it considered as a small unimportant bug that should be fixed in a future 2.0 or as a welcome leniency ?

**Comment by BurntSushi** [comment]
@Canop It might potentially be worth revisiting that, sure.

I'd say the priority on this bug is very low. I don't see this forcing a regex 2.0 release on its own.

**Comment by Canop** [comment]
I totally agree.
