### ISSUE TITLE
Unions used for type-punning should be `repr(C)`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/regex#588]
At

https://github.com/rust-lang/regex/blob/172898a4fda4fd6a2d1be9fc7b8a0ea971c84ca6/src/vector/ssse3.rs#L80-L83

a union is declared for the purpose of type-punning. However, without `repr(C)`, the fields of that union might not be at offset 0, which makes it unsuited for type punning. To get such layout guarantees, you need to specify `repr(C)`.

Also see https://rust-lang.github.io/unsafe-code-guidelines/layout/unions.html.

**Comment by gnzlbg** [comment]
So after thinking about this a bit, I believe this `union` shouldn't exist. I suppose this performs good for @BurntSushi, but that's because LLVM is able of undoing all the unnecessary work that this `union` is silently introducing. 

The problem is the following. The call ABI of this `union` is `Aggregate`and not `Vector`. That is, it will be passed via memory, just like an array (which are also `Aggregate`s), and not via a SIMD vector register. 

That is, every time you use a vector operation, which from looking at the code, happens more often than array operations, we have to copy the union from the stack to a vector register, do the operation, and copy it back to the stack. This appears to be happening all the time.

Sadly, Rust can't do better for you here, e.g., it cannot make this union have a Vector ABI. The problem is, that whether you want an Aggregate ABI or a Vector ABI depends on how you will be using this union most of the time.

Last time I heard, performance of this code is great. But that's only because LLVM is able to undo all the consecutive stack->vector->stack->vector... spills, and keep everything in a vector. Otherwise I'd guess that this would perform slower than having no vectorization at all. 

So my recommendation here would be to keep the union if most of the time you are operating on it like an array. The code appears to be operating on it almost always like a vector, though. So if that's the case, I think it would be better to commit to that, and use a type that has the Vector ABI, creating an array locally only when you need it, and being aware that this will spill the contents of the vector to the stack. 

For that you can use a type alias or a newtype for the `__m128i` type, but if you use a newtype, you need to use `repr(transparent)` here, or otherwise that type _might_ have an Aggregate ABI - I think that right now, Rust will optimize `struct(__m128i)` to have a Vector ABI (cc @eddyb), but if you want the guarantee that this optimization happens, `repr(transparent)` makes sure of that.

For copying the vector into an array and back, you probably want to just use `mem::transmute` instead of an `union`. It is safer because it checks the sizes, and it will also fix the issue with forgetting to make the `union` `repr(C)` like @RalfJung suggested above. You can obviously also use an union, but if you do, then it has to be `repr(C)`.

**Comment by BurntSushi** [comment]
@RalfJung Thanks so much for reporting this! It should be fixed in `regex 1.1.8` on crates.io.
