### ISSUE TITLE
doesn't accept [ inside bracket expression

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/regex#592]
For GNU grep `[[]` is just like `\[`, but the regex crate reports an error:
```
regex parse error:
    [[]
     ^^
error: unclosed character class
```

(I don't know if that is a GNU extension or a missing corner case in the regex crate.)

**Comment by BurntSushi** [comment]
This is by design, and there is certainly no specific goal to be compatible with POSIX regex syntax, which has a number of idiosyncrasies. For example, this regex engine supports nested character classes, such that `[[a-z]--[a-g]]` is a thing. As is `[[a-g][x-z]]`, for example. So failure modes for unescaped brackets are more important.

In general though, this crate has taken a less flexible approach to escaping in favor of better failure modes. Many regex engines will, for example, permit things that normally need to be escaped to remain unescaped if there exists an otherwise valid interpretation. (This crate does make an exception for things like `[-a-z]`, where the leading `-` is treated as a literal `-`.)
