### ISSUE TITLE
Support the 'a' flag

### ISSUE THREAD

**Issue by windelbouwman** [rust-lang/regex#598]
In python 're', there exists the 'a' flag which switches to ascii mode. It's essentially the same as the 'u' flag, or at least similar. Is there any plan to add support for this syntax?

**Comment by RReverser** [comment]
> It's essentially the same as the 'u' flag, or at least similar.

It's rather the opposite.

> Is there any plan to add support for this syntax?

Unlikely, because this is already possible with `(?-u)`.

**Comment by BurntSushi** [comment]
@windelbouwman Please describe the _desired semantics_ and how they differ from `(?-u)`.

Note that `(?-u)` is of somewhat limited utility for the `&str`-based `Regex` type. It is more useful with the `bytes::Regex` type. There is more info on its semantics here: https://docs.rs/regex/1.1.9/regex/bytes/index.html#syntax

**Comment by windelbouwman** [comment]
Basically what I'm trying to do, is implement the python `re` module in rustpython by wrapping the `regex` crate.

So my question is, how compatible will the regex crate syntax be to the python re syntax?

The corresponding code lives here:

https://github.com/RustPython/RustPython/blob/master/vm/src/stdlib/re.rs

I would like to be able to use the regex crate and use python code which uses the 'a' flag in the regex. I understand however, that the 'a' flag is sort of legacy, and that python code using this 'a' flag is legacy by design.

What I would like to prevent is to write my own regex parser for python regex, but this might be inevitable in the long run, or do you see other options to tune the parser and inject for example a mapping from the 'a' flag to '(?-u)'?

**Comment by BurntSushi** [comment]
> So my question is, how compatible will the regex crate syntax be to the python re syntax?

Not at all. Python's `re` regex engine is a backtracking engine, and it supports backreferences and look-around. There are likely other peculiarities, since `regex` supports nested character classes and character class set operations. There are also likely subtly different match semantics in corner cases, although I couldn't enumerate them off the top of my head. Additionally, Python's regex engine is likely more permissive when it comes to escaping characters, where as `regex` generally only allows escapes for meta characters.

It is a strong non-goal for this crate to bend over backwards to be compatible with other regex engines. While the dialects across all regex engines are generally similar, there are a myriad of differences when one starts to dig deeper.

If your primary goal, to the exclusion of all else, is to provide a 100% drop-in replacement for Python's `re` module written in Rust, then you should probably start by porting Python's C implementation and passing whatever test suite it has. Then build from there. Notably, simply building a custom parser won't be enough because Python's regex engine supports more things than `regex` (as mentioned above).

If that's not your primary goal, then the fact that this regex engine lacks the `a` flag is one of many differences that you'll just need to live with.

**Comment by windelbouwman** [comment]
Thanks for your explanation! I like the goal of a sort of clean, and logical implementation of regex. We will probably use it, until we face too many incompatibilities.
