### ISSUE TITLE
Support for XSD style regex

### ISSUE THREAD

**Issue by anweiss** [rust-lang/regex#608]
Any way for this library to consume XSD style regex's? I'd like to be able to take an XSD style regex string and evaluate it using this crate, but not sure if it's possible given the syntax differences between the XSD style and the Perl-style that this crate uses.

**Comment by BurntSushi** [comment]
I don't know what XSD or XSD style regexes are. Please consider adding more detail to your question, along with examples.

**Comment by anweiss** [comment]
Sure thing. I've been implementing the Concise data definitional language (CDDL) RFC 8610 at https://github.com/anweiss/cddl. The spec supports the use of XSD style regex which is defined in the XML schema definition specification at https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs. There's also a good comparison chart between the different regex flavors [here](https://gist.github.com/CMCDragonkai/6c933f4a7d713ef712145c5eb94a1816).

Below is an [example](https://www.rfc-editor.org/rfc/rfc8610.html#section-3.8.3) straight from the CDDL spec:

XSD style regex: `[A-Za-z0-9]+@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)+`

matches

`N1@CH57HF.4Znqe0.dYJRN.igjf`

**Comment by BurntSushi** [comment]
That example should work just fine in this crate.

Quickly reading the spec you linked, I'd imagine most XSD regexes will work just fine with this crate. I can see a couple small incompatibilities, for example, XSD's strange support of Unicode blocks, which are almost never the right thing to use. There are also some variations in how `.` and `\s` are defined.

If you're looking for strict 100% compatibility, then you'll need to carefully implement the spec yourself. If you're lucky, you can do it cosmetically at the syntax level, but otherwise rely on this crate's regex engine. But it is otherwise totally unreasonable for this crate to provide this for you. For example, this crate doesn't even provide POSIX compatibility, which is far more widely used than XSD.

I'd be happy to help answer questions if you have them, but otherwise I don't think there's anything to be done here in my end.
