### ISSUE TITLE
Match on char slices?

### ISSUE THREAD

**Issue by BartMassey** [rust-lang/regex#611]
For word-game-type applications, indexing of text often becomes a big deal, so iterators are not so great. For games that only use ASCII characters, the byte matcher seems great. It would be nice to be at least a little i18n, though. How hard would it be to allow `&[char]` as a match type, much as with `&[u8]` now?

(Thanks much for `regex` in any case: it's neat.)

**Comment by BurntSushi** [comment]
> How hard would it be to allow `&[char]` as a match type, much as with `&[u8]` now?

Very hard. To the point that it isn't worth it unfortunately.

You don't need to sacrifice the use of non-ASCII codepoints here though. Instead of storing `&[char]`, use `&[usize]`, where each value is an index into a `&[u8]` (or `&str`) that starts with a valid UTF-8 encoded codepoint. Then `slice[index..].chars().next().unwrap()` gives you the `char` at that position (if you need it) while being able to match on `&[u8]`/`&str` like normal. The extra storage cost is mildly unfortunate, but it should be fine for word-game-type applications, and this cost is peanuts compared to what it would cost to make the regex engines work on `&[char]`. (The assumption of `&[u8]` is baked all the way through the entire runtime.)

**Comment by BartMassey** [comment]
Makes sense, thanks.

My solver isn't worried about storage so much as access time: it's looking at a lot of chars really fast. Reassembling a `char` from its bytes can't be super-cheap, I think?

I'll probably just hand-build matchers for my specific use case rather than use REs. Thanks much for looking at this!

**Comment by BurntSushi** [comment]
It's _pretty_ cheap, but not as cheap as direct access. In any case, if storage isn't an issue, then just keeping a third slice of `&[char]` around (which runs parallel to the index slice of `&[usize]`) should be fine. Although, if you need to convert the regex match back to `&[char]` offsets, then you'll need another slice mapping byte offsets back to codepoint offsets.

_Ideally_, you wouldn't work with `&[char]` for this at all, but rather, use `&[&str]` or something of that nature. Hard to say in generic terms though.

I'm going to close this issue, but feel free to ask more questions!

**Comment by BartMassey** [comment]
Thanks much for looking at it!

I'm working on solving Hangman (in the broader sense), so there's a whole bunch of partial matches to words in dictionaries. Hand-rolled code *might* be more efficient anyhow.
