### ISSUE TITLE
Regex::bytes Emoji?

### ISSUE THREAD

**Issue by EverlastingBugstopper** [rust-lang/regex#645]
I'm trying to create a crate that checks if a string is a single emoji or not (so people don't have to hunt down the way to do that in Rust) but I'm having a hard time following the unicode docs.

What I have looks like this:

```rust
use lazy_static::lazy_static;
use regex::bytes::Regex;

pub fn is_emoji(candidate: &str) -> bool {
    lazy_static! {
        static ref REGGIE: Regex = Regex::new(r"^[\p{Emoji}]$").unwrap();
    }
    REGGIE.is_match(candidate.as_bytes())
}

#[cfg(test)]
mod tests {
    #[test]
    fn it_knows_when_you_emoji() {
        assert!(crate::is_emoji("✌🏻"));
    }

    #[test]
    fn it_knows_when_you_are_not() {
        assert!(crate::is_emoji("h"), false);
    }
}
```

unfortunately, both of these tests fail 😢 

Would love some pointers on this! Thanks 😄

**Comment by BurntSushi** [comment]
This passes:

```rust
use lazy_static::lazy_static;
use regex::Regex;

pub fn is_emoji(candidate: &str) -> bool {
    lazy_static! {
        static ref REGGIE: Regex = Regex::new(r"^\p{Emoji}+$").unwrap();
    }
    REGGIE.is_match(candidate)
}

#[cfg(test)]
mod tests {
    #[test]
    fn it_knows_when_you_emoji() {
        assert!(crate::is_emoji("✌🏻"));
    }

    #[test]
    fn it_knows_when_you_are_not() {
        assert!(!crate::is_emoji("h"));
    }
}
```

Your second assert was just ill-stated. I assume you meant to use `assert_eq!`, but it's just as well to negate the condition.

Your first assert is a bit more subtle. Many emoji are _graphemes_, which are single visual characters that are made up of one _or more_ Unicode codepoints. Your example has multiple codepoints. But the regex engine only matches one codepoint at a time. So when you ask for `^\p{Emoji}$`, you are saying, "only match strings that contain exactly one codepoint that is in the `Emoji` class." But the string you provided contains multiple emoji codepoints. So I just changed the regex to `^\p{Emoji}+$`.

Also, it would be super helpful if you could explain why you were using `regex::bytes::Regex` instead of `regex::Regex` so that I can fix the docs that led you to that. In your code, `regex::bytes::Regex` was totally unnecessary, so I removed it.

> I'm trying to create a crate that checks if a string is a single emoji or not

Some advice: if the extent of your crate is this single small function, then I would urge you to avoid publishing such micro-crates. I don't want to get into it here, but there's a thoughtful post on it here: https://lucumr.pocoo.org/2019/7/29/dependency-scaling/

**Comment by EverlastingBugstopper** [comment]
@BurntSushi - thanks for the very quick response.

re: assert v assert_eq... 🤦‍♂ 
re: where did i find docs on regex::bytes, I'm... not actually sure? I trekked through my browser history and couldn't find the culprit, it was probably a GitHub issue or something, can't find anything on legit docs pages.
re: micro-crate - the only reason it looks like this is because i separated it out for this contrived example. I'm trying to make a terminal utility crate that prints out a box with information (think [boxen](https://npmjs.com/package/boxen) and I want to find the "visual width" of a given string, and calling `.len()` on an `&str` with an emoji on it varies wildly. This is reason that I left out the `+` at the end - since I only want to test the "visual width" of a given string, while this given emoji may have two emoji codepoints, it's rendered as one. I guess the way to test that out is to test if there are two emoji codepoints right next to each other and if the second codepoint is a modifier of the first one... Yeesh.

**Comment by BurntSushi** [comment]
> re: where did i find docs on regex::bytes, I'm... not actually sure? I trekked through my browser history and couldn't find the culprit, it was probably a GitHub issue or something, can't find anything on legit docs pages.

Well, the docs for `regex::bytes` are here: https://docs.rs/regex/1.3.4/regex/bytes/index.html

What I meant was, what _led_ you to using `regex::bytes::Regex` instead of `regex::Regex`? That's the thing I'd like to correct. If you can't remember, no worries.

> and I want to find the "visual width" of a given string

I wonder if [`unicode-width`](https://docs.rs/unicode-width/0.1.7/unicode_width/) gets this right? If not, it might be worthy of a bug report, although I'm not sure if Unicode itself has a method for this that covers emojis. Discovering the actual visual width of text is generally quite tricky, and as far as I'm aware, is not possible in the general case without an actual font renderer.

**Comment by EverlastingBugstopper** [comment]
> Well, the docs for regex::bytes are here: https://docs.rs/regex/1.3.4/regex/bytes/index.html

I think I was led there because I was trying to create a regex with `\u` and was getting an error, so I switched to `regex::bytes` when I saw " (To relax this restriction, use the bytes sub-module.)" in [this section of the docs](https://docs.rs/regex/1.3.4/regex/#unicode). Actually reading the documentation would have prevented me from using it, I just generally don't know what I'm doing - wouldn't read too much into it 😄 

also i'm gonna go ahead and say that crate is good enough for what I want and that you're right that this problem is maybe a bit too difficult for a general purpose solution.

This has been fun! Thanks so much for your help 😄 see you around

**Comment by BurntSushi** [comment]
All righty, great, thanks! Always happy to hear a beginner's perspective on how crate docs can be improved. Thanks.

**Comment by EverlastingBugstopper** [comment]
fwiw i have filed an issue with `unicode_width` [here](https://github.com/unicode-rs/unicode-width/issues/17)

**Comment by wthueb** [comment]
Stumbled across this today, this fails (with any `\d+`, not just zero):

```rust
use lazy_static::lazy_static;
use regex::Regex;

pub fn is_emoji(candidate: &str) -> bool {
    lazy_static! {
        static ref REGGIE: Regex = Regex::new(r"^\p{Emoji}+$").unwrap();
    }
    REGGIE.is_match(candidate)
}

#[cfg(test)]
mod tests {
    #[test]
    fn it_knows_when_you_emoji() {
        assert!(crate::is_emoji("✌🏻"));
    }

    #[test]
    fn it_knows_when_you_are_not() {
        assert!(!crate::is_emoji("0"));
    }
}
```

This is obviously easy to work around, but I'm guessing it's not intended behavior? I am wholly unfamiliar with Unicode though.

**Comment by BurntSushi** [comment]
It's correct. Search "emoji" on this issue tracker and you'll get more information on why: 

* https://github.com/BurntSushi/ripgrep/discussions/1623#discussioncomment-28827
* https://github.com/rust-lang/regex/discussions/947
* https://github.com/rust-lang/regex/discussions/1117
* https://github.com/rust-lang/regex/issues/704
