### ISSUE TITLE
What's the idiomatic approach for Replacers that may fail?

### ISSUE THREAD

**Issue by Zireael-N** [rust-lang/regex#648]
I've been trying to reimplement the following logic in Rust: [Lua](https://github.com/hurricup/WoW-Ace3/blob/619cd1532d404f75ad4c20fbcefab6aed11e4abe/AceSerializer-3.0/AceSerializer-3.0.lua#L148), [PHP](https://github.com/SoftCreatR/WeakAuras-Decoder/blob/65c36962433ee4505110e4cb3fa7fc39c0575c81/src/SoftCreatR/WeakAuras/Decoder.php#L79-L82).

Basically, they use a regular expression to unescape some sequences and throw an exception if it's not a known one. I tried to do a similar thing but ran into an issue that `Replacer` is expected to be a function that returns `String`, not `Result<String, _>`.

I circumvented this by `panic!()`-ing inside my `Replacer` and wrapping a `replace_all()` call in [`std::panic::catch_unwind()`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) but, AFAIK, it's a pretty terrible solution.

Is there a better approach? (Other than not using regular expressions for deserializing, haha)

**Comment by BurntSushi** [comment]
It's hard for me to understand the problem you're trying to solve without seeing a complete Rust program. Could you provide a minimal reproducible example of your problem? For example, based on your description, it's not clear to me why the error needs to come at replacement time instead of being checked for before doing a replacement. I just don't understand enough about what you're trying to do.

In the general case though, this is probably your best bet: https://stackoverflow.com/questions/60068408/how-do-i-bubble-up-an-error-from-the-closure-passed-to-regexregexreplace

Which isn't ideal, especially since there is no way to stop the replacement routine. At this point, I'd recommend not using regex's replacement functionality at all. It's really provided as a convenience. Implementing replacements on top of `captures_iter` is fairly simple to do, so I'd recommend just doing that:

```rust
fn replace_all(
    re: &Regex,
    haystack: &str,
    replacement: impl Fn(&Captures) -> Result<String, Error>,
) -> Result<String, Error> {
    let mut new = String::with_capacity(haystack.len());
    let mut last_match = 0;
    for caps in re.captures_iter(haystack) {
        let m = caps.get(0).unwrap();
        new.push_str(&haystack[last_match..m.start()]);
        new.push_str(&replacement(&caps)?);
        last_match = m.end();
    }
    new.push_str(&haystack[last_match..]);
    Ok(new)
}
```

Full playground example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=196fc0d1301cb257af2bf906d869a4af

**Comment by Zireael-N** [comment]
This implementation of `replace_all` is exactly what I needed, thanks!
