### ISSUE TITLE
Consider integrating with OSS-Fuzz?

### ISSUE THREAD

**Issue by Valloric** [rust-lang/regex#650]
[OSS-Fuzz](https://google.github.io/oss-fuzz/) is a Google-provided service that can automatically and continuously fuzz OSS libraries and report bugs for discovered issues. It supports fuzzing Rust. 

[The requirement for being accepted](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/) in OSS-Fuzz is "project must have a significant user base and/or be critical to the global IT infrastructure" which I _personally_ believe definitely includes the Rust regex library, since it's at the core of so much stuff. [List of projects that are currently in OSS-Fuzz.](https://github.com/google/oss-fuzz/tree/master/projects)

Can't hurt to file a form and ask.

(Disclaimer: I work for Google, but not on anything fuzzing or security-related. I do not speak for my employer. This suggestion comes from "personal Val", not "business Val". :smiley:)

**Comment by Valloric** [comment]
Oh, forgot to mention: OSS-Fuzz offers [monetary rewards for integration](https://opensource.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html), up to $20k. If this isn't personally interesting, it can be donated to a charity of your choice and Google will double the reward.

$40k to a charity for a few days of work doesn't sound like a bad deal...

**Comment by BurntSushi** [comment]
Sounds like a good idea to me. Not sure if `regex` would qualify though or when I'll get to this. It's likely we could crib ideas from RE2: https://github.com/google/re2/tree/master/re2/fuzzing

If someone else wanted to work on this, I'd be happy to give guidance and mentor it.

**Comment by miclill** [comment]
@Valloric What kind of bugs do you hope to catch by fuzzing? It is my understanding that - since this library written without the use of unsafe - most bugs caught by fuzzing can not occur anyway. 

For reference: https://opensource.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html

**Comment by BurntSushi** [comment]
This was done in https://github.com/rust-lang/regex/pull/679

@miclill Safety bugs are not the only kind of bugs. Fuzzing is very useful for sussing out panics which should not occur.

**Comment by BurntSushi** [comment]
@DavidKorczynski The fuzzer reported its first bug: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26324

The regex it used is pretty gnarly and takes quite a long time to compile in debug mode. I think the fuzzer should run `regex` in release mode, since this is how the default size limit is mostly tuned. If a regex under the size limit takes more than 60 seconds to compile, then it's likely the size limit (or something else) needs to be tweaked.

I tried to fix this in https://github.com/rust-lang/regex/commit/9067dfd7e1d45bbb568a2d3b6975cec9e81b994f and https://github.com/rust-lang/regex/commit/44abc5f7c65a0e4919ee369970fab3c85777140d, where I changed the fuzz target to compile with optimizations. But arguably, the fuzzer itself should be building the Rust program in release mode.

Is there anything else I'm supposed to do to get the updated configuration into OSS-Fuzz? Or does it just automatically pick up changes on `master`? Thanks!

**Comment by DavidKorczynski** [comment]
The fuzzer is built by way of cargo-fuzz and the default of Cargo-fuzz is to build by way of release mode, i.e. the `--release` flag is used when calling `cargo build`: https://github.com/rust-fuzz/cargo-fuzz/blob/799bf534b889859b090b76f2ca1cffdca4ee7455/src/project.rs#L138

I did minor changes in a pull here: https://github.com/rust-lang/regex/pull/720 but once that has been merged we should be good to go with the new set up. OSS-Fuzz automatically pulls the latest, but it may take a few days.
