### ISSUE TITLE
Regex constructor that panics if it fails to compile

### ISSUE THREAD

**Issue by NickHackman** [rust-lang/regex#688]
This issue is a continuation of #450, as it seems like this would be a nice feature to add. To slightly diverge from #450, instead of replacing `Regex::new` just an alternative constructor that would return a `Regex` rather than a `Result`. Making this not a breaking change, but just a cleaner syntax for a common pattern.

This seems beneficial because in a large number of cases regular expressions are constants that are just unwrapped anyway, it should just panic instead for these cases.

# Example
**Before**:
```rust
let REGEX = Regex::new(r"regular-expression").unwrap();
```
**After**:
```rust
let REGEX = Regex::must_compile(r"regular-expression");
```

I'm not particularly taken by the `Regex::must` proposed in #450, `Regex::must_compile` is more explicit, but long. we can discuss this further.

**Comment by BurntSushi** [comment]
> This issue is a continuation of #450, as it seems like this would be a nice feature to add. To slightly diverge from #450, instead of replacing `Regex::new` just an alternative constructor that would return a `Regex` rather than a `Result`. Making this not a breaking change, but just a cleaner syntax for a common pattern.

That's exactly what #450 proposed though. It proposed _adding_ a new `Regex::must` constructor. It didn't propose removing anything or adding any breaking changes.

The main reason why I closed #450 was because I found another way to solve the problem at hand, which was producing nicer error messages. With that said, it does seem like there was positive reception to the idea.

> I'm not particularly taken by the `Regex::must` proposed in #450, `Regex::must_compile` is more explicit, but long. we can discuss this further.

I think a name like `must_compile` partially defeats the point. It still have a clearer semantics, but it's just as long as writing `Regex::new(r"...").unwrap()`.
