### ISSUE TITLE
Propage proper syntax errors downstream

### ISSUE THREAD

**Issue by kchibisov** [rust-lang/regex#691]
The original issue was started [here](https://github.com/rust-lang/regex/issues/683#issuecomment-641542345)

And there was suggested that proper syntax errors could be obtained via `regex-syntax` [here](https://github.com/rust-lang/regex/issues/683#issuecomment-641558544). However this is not really a solution, since you had to parse/translate regex twice, which is inefficient and then just always call unwrap. So having proper syntax errors without parsing things twice each time, is pretty helpful.

```rust
let regex_source = "hello(";
let hir = regex_syntax::Parser::new().parse(regex_source);
match hir {
    Err(error) => {
        println!("{:?}", error);
        return
    },
    _ => (),
}
let actual_regex = regex::Regex::new(regex_source).unwrap();
```

**Comment by BurntSushi** [comment]
"proper" syntax errors are intentionally not exposed, in order to avoid creating a public dependency on `regex-syntax`. That is certainly not going to change. The other choice is to duplicate the error types in `regex-syntax`, but the error structure is quite rich and does occasionally change. So this is also not going to happen.

Considering that access to the actual underlying structured errors is _incredibly_ niche, it seems perfectly reasonable to me for those cases to invoke `regex-syntax` directly. This is a hell of a lot more than you'll get with almost any other regex library, that's for damn sure. :-)

> since you had to parse/translate regex twice, which is inefficient

Mildly so. Parsing the regex is typically dwarfed by compiling it into a state machine, so this doesn't seem like a big deal to me. ripgrep will parse the regex twice, for example. (Not because of errors, but because of its custom inner literal detection, which requires looking at the HIR of the regex.)

> then just always call unwrap

That's not quite right, since `Regex::new` can fail for more reasons that a syntax error. The regex can be valid syntactically, but be too big to compile. That will make `regex_syntax::Parser` succeed, but `Regex::new` fail.

**Comment by kchibisov** [comment]
>Considering that access to the actual underlying structured errors is incredibly niche, it seems perfectly reasonable to me for those cases to invoke regex-syntax directly. This is a hell of a lot more than you'll get with almost any other regex library, that's for damn sure. :-)

You can provide even limited translation to something that actually makes sense. And other libraries do expose various kind of errors right from building regex(you can offset, etc). https://docs.rs/pcre2/0.2.3/pcre2/struct.Error.html#method.offset . While such thing is not perfect, it's way more useful than whatever `regex` is currently doing. I agree that exposing `regex-syntax` isn't something one could like, however having an option to not parse regex twice and provide error message that is a bit more useful outside of some CLI tools sounds like a reasonable things to ask, don't you think?

>Considering that access to the actual underlying structured errors is incredibly niche, it seems perfectly reasonable to me for those cases to invoke regex-syntax directly.

Yeah, but assume that you're live typing regex and rebuild things, rehighlight, redraw, and try to that under 7ms total, it's purely about not wasting performance, that's all.

**Comment by BurntSushi** [comment]
> Yeah, but assume that you're live typing regex and rebuild things, rehighlight, redraw, and try to that under 7ms total, it's purely about not wasting performance, that's all.

I remain unconvinced by this argument. I have zero interest in arguing about hypotheticals. If someone goes out and actually tries to build this, and they have problems, then we can tackle them then.

> And other libraries do expose various kind of errors right from building regex(you can offset, etc). https://docs.rs/pcre2/0.2.3/pcre2/struct.Error.html#method.offset

Yes, I wrote that crate (which are just bindings for PCRE2), so of course I know that. But you were asking for propagating the errors in `regex-syntax`. I don't see you asking for more condensed structured error information here. I'd be potentially open to doing something like that, but I'd like to see a use case first. (Because I suspect any such use case is going to be just fine using `regex-syntax` directly instead.)

> however having an option to not parse regex twice and provide error message that is a bit more useful outside of some CLI tools sounds like a reasonable things to ask, don't you think?

It's reasonable to ask, but I think it's also reasonable to say "no, unless you have a compelling use case to motivate it." I don't see any such use case. I see hypotheticals, but not real actionable things with measurements justifying API improvements.
