### ISSUE TITLE
Add Rust Regex flavor to regex101.com

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/regex#700]
The website <https://regex101.com/> is a great tool for testing and learning about regex.
It has many flavors: PHP, javascript, Python, Go,...
But it has no Rust to this day. 
It should be possible to add also the Rust Regex flavor for the Regex crate.
But, I don't really know about the subtle differences between this different regex engines. 
Maybe the difference is so small that an existing one could be used. Just to copy it and rename it especially for Rust.
Can somebody of the experienced developers contact that site and discuss about the flavors? 
I prepared a playground gist that could be used as a codegen on this website:
<https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=13975bff3879f843dc80d338091555b6>
Can somebody give a look at that? I wanted to show the common patterns how to use regex methods in Rust.

**Comment by BurntSushi** [comment]
I don't have any affiliation with regex101, so I'm not quite sure this ticket is actionable. I would recommend filling an issue with their project or mailing them. Feel free to CC me and I can help where I can.

Otherwise, Go's regex engine is pretty similar. The main differences are that this crate has much better Unicode support and supports more advanced character class notation (i.e., intersection, subtraction and symmetric difference).

**Comment by LucianoBestia** [comment]
I you already know another website with similar features, I would appreciate if you point me to it.
The main feature for me is the "Explanation" section: "An explanation of your regex will be automatically generated as you type". 
It makes reading, understanding, debugging and writing regex so much easier.
![image](https://user-images.githubusercontent.com/31509965/89096255-f1c53100-d3f2-11ea-891f-4efae28b8c62.png)

**Comment by BurntSushi** [comment]
I'm sorry, but I don't use regex web sites, so I don't know. As I've said a few times now, the Go regex flavor is very similar to Rust's, so if you want an explanation for a Rust regex, then select Go and it will be pretty close.
