### ISSUE TITLE
How to match \u{4}?

### ISSUE THREAD

**Issue by FrontMage** [rust-lang/regex#708]
I have some strings looks like this:
```rust
Ok("@\u{4}name\u{b}varchar(25)\u{2}NO\u{0}\u{0}")
Ok("@\u{2}id\u{19}int(10) unsigned zerofill\u{2}NO\u{0}\u{0}")
```
And I tried to remove that ' \u{2 } ' stuff.

The document says `\u` is a reserved pattern as follow
```
\u007F      hex character code (exactly four digits)
\u{7F}      any hex character code corresponding to a Unicode code point
\U0000007F  hex character code (exactly eight digits)
\U{7F}      any hex character code corresponding to a Unicode code point
```
So I try to escape that like this `let re = Regex::new(r"@?\\u\{[0-9a-z]*?\}").unwrap();`, but sadly that does not work.

Is there a way to match these things?

**Comment by BurntSushi** [comment]
> but sadly that does not work

When creating issues in projects, please never say "it doesn't work" and leave it at that. Because now I have to do the extra work if figuring out what you mean by "it doesn't work." Please _show_ me how it doesn't work.

You can do that by providing a minimal Rust program. Tell me your expected or desired output and your actual output of that program.

**Comment by FrontMage** [comment]
> > but sadly that does not work
> 
> When creating issues on projects, please never say "it doesn't work" and leave it at that. Because now I have to do the extra work if figuring out what you mean by "it doesn't work." Please _show_ me how it doesn't work.
> 
> You can do that by providing a minimal Rust program. Tell me your expected or desired output and your actual output of that program.

Sorry, my bad, here is the program.

```rust
use regex::Regex;

fn main() {
    let re = Regex::new(r"@?\\u\{[0-9a-z]*?\}").unwrap();
    let s = "@\u{2}id\u{19}int(10) unsigned zerofill\u{2}NO\u{0}\u{0}";
    // Expect s is not equal to the string after the replacing function
    // trying to remove "\u{2}" and similar stuff
    assert_eq!(s, re.replace_all(s, " "));
}

```

**Comment by BurntSushi** [comment]
Thank you. This is exactly why you should _always_ do your best to provide a compilable Rust program so that others can reproduce your exact problem, because your problem is not your regex. Your problem is what you're searching. You've written your haystack like this:

```rust
let s = "@\u{2}id\u{19}int(10) unsigned zerofill\u{2}NO\u{0}\u{0}";
```

But in Rust, `\u{2}` is itself a special escape sequence corresponding to the Unicode codepoint `U+0002`. So you either have to escape it:

```rust
let s = "@\\u{2}id\\u{19}int(10) unsigned zerofill\\u{2}NO\\u{0}\\u{0}";
```

Or use a raw string:

```rust
let s = r"@\u{2}id\u{19}int(10) unsigned zerofill\u{2}NO\u{0}\u{0}";
```

Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=43f8049430375a3068913efae7bde303

Here's more information on Rust string literals: https://doc.rust-lang.org/reference/tokens.html#literals
