### ISSUE TITLE
Support for arbitrary, proptest or similar in regex-syntax

### ISSUE THREAD

**Issue by vorner** [rust-lang/regex#712]
Hello

I wanted to fuzz an algorithm and part of the input are some regular expressions. And it's not easy right now to grab a random regular expression. So I was wondering if it could work in a way one would generate a random `Ast` from `regex-syntax` and then turn that into a regex.

But for that, the regex-syntax would need the support (for example, `arbitrary` is kind of similar to serde and expects it to be derived deep through the whole tree of types used).

What would be the maintainers' stance towards a pull request adding such support (I haven't looked at how hard it would be in practice, so I don't make any promises just yet), obviously under a feature flag?

**Comment by ethanpailes** [comment]
@vorner it might be worth checking out [proptest](https://crates.io/crates/proptest). It includes a way to generate text that matches a given regular expression (not quite what you want to do, but it could give you some ideas). If you can come up with a regex that matches regex you could even use it directly.

**Comment by BurntSushi** [comment]
@vorner regex-syntax actually used to have a somewhat hacky and internal implementation of exactly what you're describing. _Generating_ a random regex is remarkably easy. Easy enough where I don't think it would necessarily be worth even putting in the crate. _Shrinking_ a regex is much harder IIRC. But those were the days before the Ast/Hir split, so maybe shrinking an AST is easier. Not sure.

Other than that, my thoughts:

* Adding a dependency on quickcheck means adding another dependency on `rand` and I have been actively trying to avoid that. Although things do seem to have calmed down.
* quickcheck is not at 1.0 yet and not so infrequently releases breaking changes. Since it would be a public dependency of `regex-syntax`, that would also require a minor version bump of `regex-syntax`.
* quickcheck actually optionally depends on regex (or used to) through `env_logger`, so I think that means the `Arbitrary` impl would need to live inside quickcheck.

I personally would feel better about quickcheck growing an optional feature to generate a `regex-syntax::{Ast,Hir}` than I would the inverse, although I acknowledge that's not how it's typically done. But given that quickcheck already depends on regex (optionally), I imagine that's the only choice I think.

**Comment by vorner** [comment]
I was actually talking about the crate [`arbitrary`](https://crates.io/crates/arbitrary). That one doesn't depend on much (well, on the derive dependencies, but they are AFAIK all stable by now and quite calm), and it is meant to help with the `libfuzzer` integration. But I take the point of not being stable yet. I'll figure a way to make it work somehow else.
