### ISSUE TITLE
string constants

### ISSUE THREAD

**Issue by blueForestIcarus** [rust-lang/regex#748]
I'm coming here from this issue: https://github.com/BurntSushi/ripgrep/issues/1774

I think a missing feature from alot of regex engines and grep-like programs is string constants.
Say we would like to match a string `name`, but only at the begining of a line. 

We can construct a pattern `'^' + name`, but if `name` constain regex operators, it will not work as we want. 
We can, of course, escape the string `name`, but if we do not know what `name` contains, then we have to go through the string character by character, checking if it is an operator, producing a new string with the operators escaped. All this, just to have the regex engine undo it all to get back the string we started with. This not only wastes preformance, but also introduces a class of bugs resulting where you don't realise that in this flavor of regex X character needs to be escaped (and such a bug might not be caught for a long time). 

String constants would solve this problem, and make regex patterns more readable and reusable.
Using the above as the example, the pattern could be `'^{name}'`, and the regex would be executed with a dictionary `{'name':name}`.  I choose this syntax as an example of something that should not break existing patterns.

**Comment by BurntSushi** [comment]
As I explained [on the ripgrep issue tracker](https://github.com/BurntSushi/ripgrep/issues/1774#issuecomment-790615209), this feature doesn't make a lot of sense in the context of a regex library because you can get what you want with simple string interpolation:

```rust
fn main() {
    let pattern = format!("^{name}", name=regex::escape("any*data"));
    let re = regex::Regex::new(&pattern).unwrap();
    println!("{:?}", re.is_match("any*data"));
}
```

Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=24f3046b0febcb7908bbe190f4701eff



> We can, of course, escape the string `name`, but if we do not know what `name` contains, then we have to go through the string character by character, checking if it is an operator, producing a new string with the operators escaped. All this, just to have the regex engine undo it all to get back the string we started with. This not only wastes preformance

When using performance to justify an API addition, please accompany it with a benchmark. For example, in this case, I find the claim specious at best since the relative cost of escaping a string is peanuts compared to regex compilation.

> but also introduces a class of bugs resulting where you don't realise that in this flavor of regex X character needs to be escaped (and such a bug might not be caught for a long time).

Again, in the context of a regex library, this doesn't make sense. This crate exposes an [`escape`](https://docs.rs/regex/1.4.3/regex/fn.escape.html) function like all other regex libraries I'm aware of. This guarantees a completely correct escape transformation for that specific regex engine.

> and the regex would be executed with a dictionary `{'name':name}`

You mean _compiled_ with a dictionary? If you mean that the interpolation happens at _search time_, then this is a very different feature request and more easily rejected. Because it would imply re-running regex compilation for each search.

In either case, I find this suggestion to be even more odd in light of your concerns about performance. Constructing an entire dictionary at compilation time is almost certainly at least as expensive as escaping each string. Of course, both things still have a minute relative cost against regex compilation itself.

Overall, this is not a good fit for this regex library. It doesn't enable anything that can't already be done pretty easily with Rust's existing string interpolation facilities. Moreover, both of the motivating points you've provided are things that I think are non-issues in practice.

**Comment by blueForestIcarus** [comment]
I'm not sure how the internals work, but I don't see why changing the value of the constant would require recompiling the regex.

**Comment by BurntSushi** [comment]
> I'm not sure how the internals work, but I don't see why changing the value of the constant would require recompiling the regex.

I can see why someone not familiar with the internals might not think that, but it's just not the case.

> What I'm suggesting is the compilation is done once, and then the parameters are passed at search time. It does not have to be a dictionary, it could be whatever is most lightweight.

Understood. In that case, this is certainly not going to happen because it just isn't feasible.

**Comment by blueForestIcarus** [comment]
How can I get a better understanding of the internals, I want a clear understanding of why this is impossible.

**Comment by BurntSushi** [comment]
I think reading the code is probably the only way. I would recommend that you start with Russ Cox's series of articles on regexes to familiarize yourself with the higher level concepts: https://swtch.com/~rsc/regexp/

**Comment by BurntSushi** [comment]
Another thought would be to read the [Wikipedia article on DFAs](https://en.wikipedia.org/wiki/Deterministic_finite_automaton), and then check out the [`regex-automata`](https://github.com/BurntSushi/regex-automata) crate, which implements DFAs. It might be an easier pill to swallow here, since the runtime environment (meaning, the environment in which a regex is executed for a search) is extremely simple. So it might be easier to connect the dots on why simply interpolating literals won't work---because the finite state machine would have to be re-built.

Now, the `regex` crate doesn't use classical DFAs directly, but it _does_ use a lazy DFA, which builds a DFA at search time and caches the states. Building the DFA assumes that the underlying regex remains invariant across searches, so if we added a feature that permitted interpolation, that assumption would no longer be true. So the DFA would have to be constantly re-built and would thus either hurt performance or increase memory usage substantially.

I think that alone is enough to understand why your requested feature is problematic, but it's actually not the only reason. Other reasons include:

* This crate does fairly sophisticated analysis of the regex to extract literals from the pattern to execute searches more quickly by using a fast prefilter based on those literals. Interpolation would invalidate this feature.
* The NFA and its corresponding simulation does not store things like `foo` in the regex `^foo` as one contiguous block of memory. So it cannot just be replaced. Instead, it has op-code instructions for each individual character, e.g., `f` -> `o` -> `o`. So that portion of the regex, at least, would need to be-recompiled at search time in the presence of interpolation. Either that, or new op-code instructions would need to be introduced specifically to support interpolation.

There are likely other problems that even I'm not thinking about. This is the kind of thing that digs deep into fundamental assumptions about the search environment. It's not unreasonable to see why: the search environment has an assumption that the underlying machine remains invariant across searches. Thus, the vast majority of not just the code but the entire design of the regex engine gets written with that assumption in mind. So breaking that assumption requires rethinking all code that was written with that assumption in mind. (I note that this does not cover all such problems above. For example, interpolating a literal into a DFA is literally not possible in general without rebuilding the DFA.)

Building a regex engine with your specific feature in mind would require a different design, most likely, and likely sacrifice at least some optimization opportunities. It would be an interesting endeavor, but I suspect the reason why it hasn't been done is that the feature you're requesting just isn't useful or common enough. It typically can be worked around by just compiling more regexes. If that doesn't work, then a more specialized solution that doesn't need regexes might work better.

**Comment by BurntSushi** [comment]
And even putting aside the issue of whether it's feasible to implement this or not, the API being requested I _believe_ requires one to duplicate most of the API of the existing search routines. For example, you'd need `find` and `find_interpolate`, where the latter accepts a map for the interpolation. Even on that grounds alone, I'd probably reject this feature _even if it were easy to implement_ simply because the added complexity by virtue of a bigger API surface isn't worth solving such a niche use case.
