### ISSUE TITLE
Word boundary around some symbols

### ISSUE THREAD

**Issue by dalance** [rust-lang/regex#755]
#### What version of regex are you using?

regex 1.4.5

#### Describe the bug at a high level.

`\b` around symbol doesn't match the end of string.
http://www.unicode.org/reports/tr29/#WB2 seems to say the end of string is word boundary.

#### What are the steps to reproduce the behavior?

```rust
use regex::Regex;

fn main() {
    let re = Regex::new(r"hello").unwrap();
    dbg!(re.is_match("hello"));
    let re = Regex::new(r"hello\b").unwrap();
    dbg!(re.is_match("hello"));

    let re = Regex::new(r"\.").unwrap();
    dbg!(re.is_match("."));
    let re = Regex::new(r"\.\b").unwrap();
    dbg!(re.is_match("."));
}
```

#### What is the actual behavior?

```console
$ cargo run
[src/main.rs:5] re.is_match("hello") = true
[src/main.rs:7] re.is_match("hello") = true
[src/main.rs:10] re.is_match(".") = true
[src/main.rs:12] re.is_match(".") = false
```

#### What is the expected behavior?

I think all outputs should be `true`.

**Comment by BurntSushi** [comment]
I don't understand why you have that expectation. The behavior is consistent with the [documentation](https://docs.rs/regex/1.4.5/regex/#empty-matches):

> a Unicode word boundary (\w on one side and \W, \A, or \z on other)

Since `.` is not in `\w`, your last example does not and should not match.

Finally, your Unicode link is not quite right. See: https://github.com/rust-lang/regex/blob/master/UNICODE.md#rl14-simple-word-boundaries

**Comment by dalance** [comment]
I got the following result. I think this is not consistent with the [documentation](https://docs.rs/regex/1.4.5/regex/#empty-matches).

```rust
use regex::Regex;

fn main() {
    let re = Regex::new(r"\.\b").unwrap();
    dbg!(re.is_match("."));
    let re = Regex::new(r"\.\z").unwrap();
    dbg!(re.is_match("."));
}
```

```console
$ cargo run
[src/main.rs:5] re.is_match(".") = false
[src/main.rs:7] re.is_match(".") = true
```

The documentation says `\b` includes `\z`. Why is there the difference of the behavior between `\.\z` and `\.\b`.

**Comment by dalance** [comment]
I think `\.` should be matched with `.` and `\b` should be matched with the end of string.

**Comment by BurntSushi** [comment]
@dalance You are misunderstanding the docs. I'll try to spell it out in more detail. A `\b` assertion is defined as follows. Given a position `i` in `haystack`, then:

* If `i == 0`, then `i` is a word boundary whenever `haystack[i]` is in `\w`.
* If `i == haystack.len()`, then `i` is a word boundary whenever `haystack[haystack.len() - 1]` is in `\w`.
* In all other cases, `i` is a word boundary whenever one of the following holds:
    * `haystack[i - 1]` is in `\w` AND `haystack[i]` is NOT in `\w`.
    * `haystack[i - 1]` is NOT in `\w` AND `haystack[i]` is in `\w`.

A more succinct way to describe the above is to say that `i` is a word boundary if and only if one side of it is in `\w` and the other side is either in `\W` or is the beginning (that is, `\A`) or end (that is, `\z`) of the haystack. Therefore, saying something like "`\b` includes `\z`" doesn't quite make sense. `\z` is merely _part_ of the definition of `\b`, but `\z` is neither necessary nor sufficient for `\b` to hold.

Consider using the above definition with your examples. Your first regex is `\.\b` and the haystack is `.`. Since `.` is not in `\w`, it follows that `\b` can never match. Your second regex is `\.\z` and the haystack is `.`. Since `\z` always matches at the end of the haystack and `.` is the last character in the haystack, `\.\z` matches.

**Comment by dalance** [comment]
@BurntSushi Thank you for the detailed explanation. I understand it.
