### ISSUE TITLE
Add support for Option<String> for replacer

### ISSUE THREAD

**Issue by ModProg** [rust-lang/regex#809]
#### Describe your feature request
I am matching all matches to a specific regex and then decide programicly if I actually want to replace this word, if not, I want to just return None and keep the current word where it is.

My proposed implementation would be implement `Replacer` for `Option`.

**Comment by BurntSushi** [comment]
Please provide some code that shows what you need to do. Please also describe, at a high level, the problem you're trying to solve.

**Comment by ModProg** [comment]
Iterate over all matches of a String, and then decide programmatically whether to actually replace the match or not:

```rs
    /// Replaces all emotes in the `message` given
    #[cfg(feature = "regex")]
    pub fn replace_all<'a>(&self, message: &'a str) -> Cow<'a, str> {
        lazy_static! {
            static ref RE: Regex = Regex::new(r"[^,.\s]*").unwrap();
        }

        RE.replace_all(message, |w: &Captures| {
            self.to_string(w.get(0).unwrap().as_str()).unwrap_or_else(|| w.get(0).unwrap().as_str().to_owned())
        })
    }
```

**Comment by BurntSushi** [comment]
OK, so looking at this more closely, your question is ill-formed. You don't seem to be asking to `impl Replacer for OptionString>`, but rather, you want to `impl Replacer for FnMut(&Captures<'_>) -> Option<T> where T: AsRef<str>`. As far as I know, this isn't possible, because it overlaps with the existing impl.

In any case, if you want to replace a match with nothing, then you can just return the empty string. If you're concerned about performance, then you shouldn't be using the convenient closure syntax in the first place and should instead be implementing `Replacer` yourself. This case is then handled by simply not pushing any new data to `dst` in the impl of `replace_append`.

**Comment by ModProg** [comment]
> OK, so looking at this more closely, your question is ill-formed. You don't seem to be asking to `impl Replacer for Option<String>`, but rather, you want to `impl Replacer for FnMut(&Captures<'_>) -> Option<T> where T: AsRef<str>`. As far as I know, this isn't possible, because it overlaps with the existing impl.

You are correct, my bad. I thought there was a `impl<F: FnMut(&Captures<'_>, T: Replacement> Replacer for F` and `Replacement` could be implemented for `Option<T: AsRef<str>` but now looking at the code that would not be possible.

> In any case, if you want to replace a match with nothing, then you can just return the empty string.

I don't want to replace it with nothing, I want to replace it with itself, i.e. do nothing.

**Comment by BurntSushi** [comment]
> I don't want to replace it with nothing, I want to replace it with itself, i.e. do nothing.

I guess that's another reason not to do this, because there are two sensible ways to interpret `Option<String>`. But yeah, you can accomplish this by just slicing the part of the haystack you want.
