### ISSUE TITLE
Matching significantly slower vs pcre1

### ISSUE THREAD

**Issue by mrmonday** [rust-lang/regex#827]
Via: https://www.reddit.com/r/cpp/comments/rw93sj/added_stdregex_to_a_regex_shootout_and_the/

I've hacked the anomalous looking test into the benchmarking suite in a branch here: https://github.com/mrmonday/regex/tree/reddit-twain-match (specific commit: https://github.com/mrmonday/regex/commit/92d390095911975d7988ecca69707a3c444c7c47)

The regex in question is: `[a-q][u-z]{13}x`. There are no matches, so I suspect this can be replicated with any sufficiently large body of text.

Results:
```
$ ./run pcre1
test twain ... bench:   1,077,360 ns/iter (+/- 12,987) = 14864 MB/s
$ ./run rust
test twain ... bench:  20,183,304 ns/iter (+/- 234,879) = 793 MB/s
```

**Comment by BurntSushi** [comment]
> There are no matches, so I suspect this can be replicated with any sufficiently large body of text.

Certainly not. :-) There are many variables that go into perf of regex, and the size of the text is just one of them. In this particular case, the issue is the regex itself. A variant of this class of problem is already captured in the existing benchmark suite. See [pcre1::repeated_class_negation](https://github.com/rust-lang/regex/blob/5197f21287344d2994f9cf06758a3ea30f5a26c3/bench/log/07/pcre1#L89) and [rust::repeated_class_negation](https://github.com/rust-lang/regex/blob/5197f21287344d2994f9cf06758a3ea30f5a26c3/bench/log/07/rust#L104). The benchmark is [defined here with a comment giving a brief analysis](https://github.com/rust-lang/regex/blob/5197f21287344d2994f9cf06758a3ea30f5a26c3/bench/src/sherlock.rs#L207-L218).

The issue here is likely the bounded repeat. It generally explodes the size of the finite state machine and makes it difficult to execute quickly.

That's not to say that it can't be fixed, but it isn't currently something I'm focusing on. I'm also not sure it makes sense to track "bugs" like this, since _all_ regex engines will generally be faster and slower than other regex engines in at least some cases.

**Comment by pdimov** [comment]
I couldn't help but notice that the comment says "RE2 does a worse job so we disable it" but the Reddit table shows RE2 performing adequately (72.3 compared to ~400 for PCRE).

**Comment by BurntSushi** [comment]
That's plausible. I wrote that comment years ago. That's why benchmark analysis is difficult: it can quickly become out of date and it is expensive to fix that.
