### ISSUE TITLE
Why are some invalid regex-es qualified as valid?

### ISSUE THREAD

**Issue by Arian94** [rust-lang/regex#847]
#### What version of regex are you using?

1.5.4

#### Describe the bug at a high level.

For instance, the regex ```adsa+*``` is invalid, however the regex builder outputs no error, no panic. 
Why is that?

#### What are the steps to reproduce the behavior?

```
let a = regex::RegexBuilder::new("adsa+*");
regex::RegexBuilder::build(&a).unwrap();    // must panic
 ```

#### What is the actual behavior?

No panic.

#### What is the expected behavior?

To panic.

**Comment by BurntSushi** [comment]
> For instance, the regex `adsa+*` is invalid

What makes you say that? Where are you getting your definition of "valid" from?

**Comment by BurntSushi** [comment]
regex101 doesn't have a Rust flavor:

![regex101](https://user-images.githubusercontent.com/456674/157096833-d3d43574-4699-4e9f-a5a6-48c35f3fe3b5.png)

so I don't see how you could use it to determine which regexes are valid for this crate and which aren't.

> `ads{2,8}{6}`
> Is this a valid regex??

Yes.

**Comment by Arian94** [comment]
It does not support Rust but the thing is ```ads{2,8}{6}``` is invalid for all the above-mentioned languages but Rust and that's strange to me.
It is said that this crate is a Perl-like regex. I'm just checking this very expression in
https://ingram-braun.net/erga/online-regex-tester-perl-php-javascript/
and still I'm getting invalid regex error.

If Rust Regex is that different, a book or something is substantially needed. Something I couldn't have found on the internet.

**Comment by BurntSushi** [comment]
> If Rust Regex is that different

It isn't.

In general, no two regex engines have the same set of valid regexes. And sometimes, even for two regexes that have equivalent concrete syntax, their behavior might be different depending on the regex engine. Additionally, Rust's regex engine also rejects some regexes that other regex engines don't. For example, `a{` is typically a valid regex for most engines, but it is invalid for this one.

> a book or something is substantially needed

I'm always in favor of improving docs. And I think it would be nice to have a "beginner" level tutorial focused around the regex crate. (I believe there's an issue tracking that.) But pretty much any beginner regex tutorial will be sufficient for at least learning the regex syntax and behavior in 99% of the cases. The cases you bring up here are niche, and I very strong reject your claim that a book is "substantially" needed based on the evidence you've presented so far.

Otherwise, I'll close this in favor of #497.

**Comment by BurntSushi** [comment]
See also: #765.

**Comment by Arian94** [comment]
I know how to read regex. No need for beginner tutorial. Thank you very much.
Just wanted to make my point.
Those tables of definitions in the crate documentation itself for things like Grouping, alternation etc. is just so basic. There could've been an interpreter like regex101 so that one could find why the weird regex I mentioned in the first place is valid, consequently stopping me from making this issue which I knew was out-of-context and basically was not a bug to be honest.
Fair to say I shouldn't have opened this issue at all but this kind of extreme impressions (e.g.  very strongly reject) makes me lose my interest in continuing development of Rust programs.
