### ISSUE TITLE
Allow escaping `#` when using the x flag

### ISSUE THREAD

**Issue by killercup** [rust-lang/regex#88]
It's nothing really important, but it would be nice if one could escape a literal `#` so it doesn't start a comment when using the `x` flag.

The current workaround is using the ASCII literal `\x23`, but something like `\#` would be clearer.

Workaround example:

```rust
let markdown_headline = regex!(r"(?x)
    ^
    (?P<level>[\x23]+)  # A bunch of hash symbols
    \s
    (?P<title>.+)       # Title
    $
");
```

**Comment by BurntSushi** [comment]
Seems reasonable! I think adding `#` to [`is_punct`](https://github.com/rust-lang/regex/blob/master/regex-syntax/src/parser.rs#L1059) should do the trick.

**Comment by killercup** [comment]
Cool! I'll give it a try.

**Comment by BurntSushi** [comment]
@killercup If you can write a test for it that passes, then that's great. But on second thought, it might be a bit trickier than that. The problem is that insignificant whitespace/comments are handled at a layer below the parser: https://github.com/rust-lang/regex/blob/master/regex-syntax/src/parser.rs#L804-L818 So I think the mini-state machine in the `skip` method will need to be made aware of the escape. (But `#` should still be part of `is_punct`.)

If you get bogged down, no worries and I can take a crack at it later.
