### ISSUE TITLE
look-ahead and look-behind

### ISSUE THREAD

**Issue by zyede** [rust-lang/regex#964]
#### regex rule look-ahead and look-behind not supported?

example:
i have a text, and want to match zhe json str
```
jsonpgz({"fundcode":"000924"});
```
re:
```
(?<=jsonpgz\()(.+)(?=\);)
```

rust code:
```
let re = Regex::new("(?<=jsonpgz\\()(.+)(?=\\);)").unwrap();
let fund_json_str = re.captures("jsonpgz({"fundcode":"000924"});").unwrap();
```
run error:
```
look-around, including look-ahead and look-behind, is not supported
```
![image](https://user-images.githubusercontent.com/17783147/223073122-2e808148-724f-4fee-8806-20cd5fc47aee.png)

**Comment by BurntSushi** [comment]
I'm not sure what this issue is asking for. Both the error message and crate docs make it pretty clear that look around isn't supported. See also: https://github.com/rust-lang/regex/discussions/910

And in your specific example here, it's not clear to me why you're even using look around in the first place. You already using capture groups. So just pluck out the capture group that matches the JSON.
