### ISSUE TITLE
How to determine if replacement occurred

### ISSUE THREAD

**Issue by aswild** [rust-lang/regex#966]
When using `Regex::replace` methods (including `replace_all` and `replacen`), is it possible to reliably determine whether any replacements occurred? If not, could such a capability be added?

For example, consider this hypothetical function signature

```rust
/// Return Some if a replacement was made, None if there was no match
fn maybe_replace(re: &Regex, text: &str, repl: &str) -> Option<String>;
```

This naive implementation would work, but performs the regex search twice, once during `is_match` and again in `replace`.

```rust
if re.is_match(text) {
    Some(re.replace(text, repl).into_owned())
} else {
    None
}
```

Looking at the implementation of `replacen`, it seems like `Cow::Borrowed` is always returned when there's no match, and `Cow::Owned` is always returned when at least one replacement is made.

```rust
match re.replace(text, repl) {
    Cow::Borrowed(_) => None,
    Cow::Owned(s) => Some(s),
}
```

It seems like this `Cow` function would work, but that feels like depending on implementation details. Could this behavior be codified and documented as an API guarantee?

Alternatively, what about a new API that performs replacement and returns the number of replacements made, e.g.

```rust
pub fn replacen_count<'t, R: Replacer>(
    &self,
    text: &'t str,
    limit: usize,
    rep: R
) -> (Cow<'t, str>, usize);
```

The same applies to the bytes-based Regex implementation too. I'm willing to send a PR if there's interest in supporting this.

**Comment by BurntSushi** [comment]
Have you looked into implementing the Replacer trait?

> Could this behavior be codified and documented as an API guarantee?

I would rather not. Certainly, when the borrowed variant is returned, then you know no replacements have been made. But it's possible a future implementation might return an owned variant without making any replacements.

> Alternatively, what about a new API that performs replacement and returns the number of replacements made

No, for two reasons. First is that the use case looks quite niche (although you haven't elaborated on the actual problem you're trying to solve). Second is that the code for doing replacements is not really that complicated. And it's short. If you need a different behavior, then just write the code yourself. It doesn't make sense to support all different flavors of replacement here. Otherwise it makes it too easy for folks to get confused about which method to use. There are always three different generic replacement routines. That's enough.

**Comment by BurntSushi** [comment]
Yeah it looks to be like you could get what you want with a custom implementation of the Replacer trait. Or even with just the existing closure implementation. Just count the number of times it's called.

**Comment by aswild** [comment]
Thanks for your reply and consideration - understandable logic on both counts.

I'll look into making a custom Replacer adapter or some other logic for my use case (which is similar to `perl -ne 'print if s/pattern/replacement/'`)

**Comment by BurntSushi** [comment]
Now that I have my hands on a keyboard, as I said, you don't need a custom `Replacer` impl. You can just use the existing support for closures. For example, this program runs and its asserts pass:

```rust
use regex::Regex;

fn main() {
    let re = Regex::new(r"\b\w+\b").unwrap();
    let hay = "The bright lights of Memphis.";

    let mut count = 0;
    let result = re.replace_all(hay, |_: &regex::Captures| {
        count += 1;
        "x".to_string()
    });
    assert_eq!("x x x x x.", result);
    assert_eq!(5, count);
}
```
