### ISSUE TITLE
three regular expressions consume 37M memory

### ISSUE THREAD

**Issue by maxbear1988** [rust-lang/regex#986]
#### What version of regex are you using?
1.5.5
If it isn't the latest version, then please upgrade and check whether the bug
is still present.
yes
#### Describe the bug at a high level.

Give a brief description of the actual problem you're observing.
 
three regular expressions consume 37M memory

#### What are the steps to reproduce the behavior?

fn main() {
    println!("regex start!");
    let x = Regex::new(r"^.{1,255}$");
    let y = Regex::new(r"^.{1,5000}$");
    let z = Regex::new(r"^.{1,3000}$");
    println!("regex end!");
}

This section should almost always provide a COMPLETE Rust program that others
can compile and run with Cargo. It should be as small as possible.

If providing a small and simple reproduction is not easy, please explain why
and the maintainers will help you figure out next steps.

#### What is the actual behavior?

If you provide a Rust program in the previous section, then this should be the
output of that program.
cost 37M memory

#### What is the expected behavior?

What do you expect the output to be?

**Comment by BurntSushi** [comment]
Well, yes, because those regexes are _huge_ finite state machines. The NFA for `^.{1,5000}$` contains over 40,000 states! You could substantially reduce that to about 5,000 states with `^[\p{ascii}--\n]{1,5000}$` if you only care about ASCII. By default, `.` is a UTF-8 automaton that matches any UTF-8 encoding of a Unicode scalar value (except for `\n`).
